# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.models.vision_transformer
# (timm 1.0.22, source sha256 fbbfd91ae654ec3d).  Do not edit; change the spec.
# Kept: Block, VisionTransformer, checkpoint_filter_fn, _create_vision_transformer, vit_small_patch16_224, vit_giant_patch14_224, vit_base_patch16_siglip_256, vit_base_patch14_dinov2
from __future__ import absolute_import, division, print_function
import math
import os
from functools import partial
import torch
import torch.nn as nn
from timm.layers import Attention, AttentionPoolLatent, PatchEmbed, Mlp, LayerNorm, DropPath, calculate_drop_path_rates, PatchDropout, trunc_normal_, lecun_normal_, resample_patch_embed, resample_abs_pos_embed, get_act_layer, get_norm_layer, LayerScale
from timm.models._builder import build_model_with_cfg
from timm.models._features import feature_take_indices
from timm.models._manipulate import named_apply, checkpoint, checkpoint_seq, adapt_input_conv
from timm.models._registry import register_model

class Block(nn.Module):
    """Transformer block with pre-normalization."""

    def __init__(self, dim, num_heads, mlp_ratio=4.0, qkv_bias=False, qk_norm=False, scale_attn_norm=False, scale_mlp_norm=False, proj_bias=True, proj_drop=0.0, attn_drop=0.0, init_values=None, drop_path=0.0, act_layer=nn.GELU, norm_layer=LayerNorm, mlp_layer=Mlp, device=None, dtype=None):
        """Initialize Block.

        Args:
            dim: Number of input channels.
            num_heads: Number of attention heads.
            mlp_ratio: Ratio of mlp hidden dim to embedding dim.
            qkv_bias: If True, add a learnable bias to query, key, value.
            qk_norm: If True, apply normalization to query and key.
            proj_bias: If True, add bias to output projection.
            proj_drop: Projection dropout rate.
            attn_drop: Attention dropout rate.
            init_values: Initial values for layer scale.
            drop_path: Stochastic depth rate.
            act_layer: Activation layer.
            norm_layer: Normalization layer.
            mlp_layer: MLP layer.
        """
        super(Block, self).__init__()
        dd = {'device': device, 'dtype': dtype}
        self.norm1 = norm_layer(dim, **dd)
        self.attn = Attention(dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_norm=qk_norm, scale_norm=scale_attn_norm, proj_bias=proj_bias, attn_drop=attn_drop, proj_drop=proj_drop, norm_layer=norm_layer, **dd)
        self.ls1 = LayerScale(dim, init_values=init_values, **dd) if init_values else nn.Identity()
        self.drop_path1 = DropPath(drop_path) if drop_path > 0.0 else nn.Identity()
        self.norm2 = norm_layer(dim, **dd)
        self.mlp = mlp_layer(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer, norm_layer=norm_layer if scale_mlp_norm else None, bias=proj_bias, drop=proj_drop, **dd)
        self.ls2 = LayerScale(dim, init_values=init_values, **dd) if init_values else nn.Identity()
        self.drop_path2 = DropPath(drop_path) if drop_path > 0.0 else nn.Identity()

    def forward(self, x, attn_mask=None):
        x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x), attn_mask=attn_mask)))
        x = x + self.drop_path2(self.ls2(self.mlp(self.norm2(x))))
        return x

def global_pool_nlc(x, pool_type='token', num_prefix_tokens=1, reduce_include_prefix=False):
    if not pool_type:
        return x
    if pool_type == 'token':
        x = x[:, 0]
    else:
        x = x if reduce_include_prefix else x[:, num_prefix_tokens:]
        if pool_type == 'avg':
            x = x.mean(dim=1)
        elif pool_type == 'avgmax':
            x = 0.5 * (x.amax(dim=1) + x.mean(dim=1))
        elif pool_type == 'max':
            x = x.amax(dim=1)
        else:
            assert not pool_type, 'Unknown pool type {0}'.format(pool_type)
    return x

class VisionTransformer(nn.Module):
    """ Vision Transformer

    A PyTorch impl of : `An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale`
        - https://arxiv.org/abs/2010.11929
    """

    def __init__(self, img_size=224, patch_size=16, in_chans=3, num_classes=1000, global_pool='token', embed_dim=768, depth=12, num_heads=12, mlp_ratio=4.0, qkv_bias=True, qk_norm=False, scale_attn_norm=False, scale_mlp_norm=False, proj_bias=True, init_values=None, class_token=True, pos_embed='learn', no_embed_class=False, reg_tokens=0, pre_norm=False, final_norm=True, fc_norm=None, pool_include_prefix=False, dynamic_img_size=False, dynamic_img_pad=False, drop_rate=0.0, pos_drop_rate=0.0, patch_drop_rate=0.0, proj_drop_rate=0.0, attn_drop_rate=0.0, drop_path_rate=0.0, weight_init='', fix_init=False, embed_layer=PatchEmbed, embed_norm_layer=None, norm_layer=None, act_layer=None, block_fn=Block, mlp_layer=Mlp, device=None, dtype=None):
        """
        Args:
            img_size: Input image size.
            patch_size: Patch size.
            in_chans: Number of image input channels.
            num_classes: Number of classes for classification head.
            global_pool: Type of global pooling for final sequence (default: 'token').
            embed_dim: Transformer embedding dimension.
            depth: Depth of transformer.
            num_heads: Number of attention heads.
            mlp_ratio: Ratio of mlp hidden dim to embedding dim.
            qkv_bias: Enable bias for qkv projections if True.
            init_values: Layer-scale init values (layer-scale enabled if not None).
            class_token: Use class token.
            no_embed_class: Don't include position embeddings for class (or reg) tokens.
            reg_tokens: Number of register tokens.
            pre_norm: Enable norm after embeddings, before transformer blocks (standard in CLIP ViT).
            final_norm: Enable norm after transformer blocks, before head (standard in most ViT).
            fc_norm: Move final norm after pool (instead of before), if None, enabled when global_pool == 'avg'.
            drop_rate: Head dropout rate.
            pos_drop_rate: Position embedding dropout rate.
            attn_drop_rate: Attention dropout rate.
            drop_path_rate: Stochastic depth rate.
            weight_init: Weight initialization scheme.
            fix_init: Apply weight initialization fix (scaling w/ layer index).
            embed_layer: Patch embedding layer.
            embed_norm_layer: Normalization layer to use / override in patch embed module.
            norm_layer: Normalization layer.
            act_layer: MLP activation layer.
            block_fn: Transformer block layer.
        """
        super(VisionTransformer, self).__init__()
        dd = {'device': device, 'dtype': dtype}
        assert global_pool in ('', 'avg', 'avgmax', 'max', 'token', 'map')
        assert class_token or global_pool != 'token'
        assert pos_embed in ('', 'none', 'learn')
        use_fc_norm = global_pool in ('avg', 'avgmax', 'max') if fc_norm is None else fc_norm
        norm_layer = get_norm_layer(norm_layer) or LayerNorm
        embed_norm_layer = get_norm_layer(embed_norm_layer)
        act_layer = get_act_layer(act_layer) or nn.GELU
        self.num_classes = num_classes
        self.global_pool = global_pool
        self.num_features = self.head_hidden_size = self.embed_dim = embed_dim
        self.num_prefix_tokens = 1 if class_token else 0
        self.num_prefix_tokens += reg_tokens
        self.num_reg_tokens = reg_tokens
        self.has_class_token = class_token
        self.no_embed_class = no_embed_class
        self.pool_include_prefix = pool_include_prefix
        self.dynamic_img_size = dynamic_img_size
        self.grad_checkpointing = False
        embed_args = {}
        if dynamic_img_size:
            embed_args.update(dict(strict_img_size=False, output_fmt='NHWC'))
        if embed_norm_layer is not None:
            embed_args['norm_layer'] = embed_norm_layer
        self.patch_embed = embed_layer(img_size=img_size, patch_size=patch_size, in_chans=in_chans, embed_dim=embed_dim, bias=not pre_norm, dynamic_img_pad=dynamic_img_pad, **dict(list(embed_args.items()) + list(dd.items())))
        num_patches = self.patch_embed.num_patches
        reduction = self.patch_embed.feat_ratio() if hasattr(self.patch_embed, 'feat_ratio') else patch_size
        self.cls_token = nn.Parameter(torch.zeros(1, 1, embed_dim, **dd)) if class_token else None
        self.reg_token = nn.Parameter(torch.zeros(1, reg_tokens, embed_dim, **dd)) if reg_tokens else None
        embed_len = num_patches if no_embed_class else num_patches + self.num_prefix_tokens
        if not pos_embed or pos_embed == 'none':
            self.pos_embed = None
        else:
            self.pos_embed = nn.Parameter(torch.randn(1, embed_len, embed_dim, **dd) * 0.02)
        self.pos_drop = nn.Dropout(p=pos_drop_rate)
        if patch_drop_rate > 0:
            self.patch_drop = PatchDropout(patch_drop_rate, num_prefix_tokens=self.num_prefix_tokens)
        else:
            self.patch_drop = nn.Identity()
        self.norm_pre = norm_layer(embed_dim, **dd) if pre_norm else nn.Identity()
        dpr = calculate_drop_path_rates(drop_path_rate, depth)
        self.blocks = nn.Sequential(*[block_fn(dim=embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, qkv_bias=qkv_bias, qk_norm=qk_norm, scale_attn_norm=scale_attn_norm, scale_mlp_norm=scale_mlp_norm, proj_bias=proj_bias, init_values=init_values, proj_drop=proj_drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[i], norm_layer=norm_layer, act_layer=act_layer, mlp_layer=mlp_layer, **dd) for i in range(depth)])
        self.feature_info = [dict(module='blocks.{0}'.format(i), num_chs=embed_dim, reduction=reduction) for i in range(depth)]
        self.norm = norm_layer(embed_dim, **dd) if final_norm and (not use_fc_norm) else nn.Identity()
        if global_pool == 'map':
            self.attn_pool = AttentionPoolLatent(self.embed_dim, num_heads=num_heads, mlp_ratio=mlp_ratio, norm_layer=norm_layer, act_layer=act_layer, **dd)
        else:
            self.attn_pool = None
        self.fc_norm = norm_layer(embed_dim, **dd) if final_norm and use_fc_norm else nn.Identity()
        self.head_drop = nn.Dropout(drop_rate)
        self.head = nn.Linear(self.embed_dim, num_classes, **dd) if num_classes > 0 else nn.Identity()
        if weight_init != 'skip':
            self.init_weights(weight_init)
        if fix_init:
            self.fix_init_weight()

    def fix_init_weight(self):
        """Apply weight initialization fix (scaling w/ layer index)."""

        def rescale(param, _layer_id):
            param.div_(math.sqrt(2.0 * _layer_id))
        for layer_id, layer in enumerate(self.blocks):
            rescale(layer.attn.proj.weight.data, layer_id + 1)
            rescale(layer.mlp.fc2.weight.data, layer_id + 1)

    def init_weights(self, mode=''):
        """Initialize model weights.

        Args:
            mode: Weight initialization mode ('jax', 'jax_nlhb', 'moco', or '').
        """
        assert mode in ('jax', 'jax_nlhb', 'moco', '')
        head_bias = -math.log(self.num_classes) if 'nlhb' in mode else 0.0
        if self.pos_embed is not None:
            trunc_normal_(self.pos_embed, std=0.02)
        if self.cls_token is not None:
            nn.init.normal_(self.cls_token, std=1e-06)
        if self.reg_token is not None:
            nn.init.normal_(self.reg_token, std=1e-06)
        named_apply(get_init_weights_vit(mode, head_bias), self)

    def _init_weights(self, m):
        """Initialize weights for a single module (compatibility method)."""
        init_weights_vit_timm(m)

    @torch.jit.ignore()
    def load_pretrained(self, checkpoint_path, prefix=''):
        """Load pretrained weights.

        Args:
            checkpoint_path: Path to checkpoint.
            prefix: Prefix for state dict keys.
        """
        _load_weights(self, checkpoint_path, prefix)

    @torch.jit.ignore
    def no_weight_decay(self):
        """Set of parameters that should not use weight decay."""
        return {'pos_embed', 'cls_token', 'dist_token'}

    @torch.jit.ignore
    def group_matcher(self, coarse=False):
        """Create regex patterns for parameter grouping.

        Args:
            coarse: Use coarse grouping.

        Returns:
            Dictionary mapping group names to regex patterns.
        """
        return dict(stem='^cls_token|pos_embed|patch_embed', blocks=[('^blocks\\.(\\d+)', None), ('^norm', (99999,))])

    @torch.jit.ignore
    def set_grad_checkpointing(self, enable=True):
        """Enable or disable gradient checkpointing.

        Args:
            enable: Whether to enable gradient checkpointing.
        """
        self.grad_checkpointing = enable
        if hasattr(self.patch_embed, 'set_grad_checkpointing'):
            self.patch_embed.set_grad_checkpointing(enable)

    @torch.jit.ignore
    def get_classifier(self):
        """Get the classifier head."""
        return self.head

    def reset_classifier(self, num_classes, global_pool=None):
        """Reset the classifier head.

        Args:
            num_classes: Number of classes for new classifier.
            global_pool: Global pooling type.
        """
        self.num_classes = num_classes
        if global_pool is not None:
            assert global_pool in ('', 'avg', 'avgmax', 'max', 'token', 'map')
            if global_pool == 'map' and self.attn_pool is None:
                assert False, 'Cannot currently add attention pooling in reset_classifier().'
            elif global_pool != 'map' and self.attn_pool is not None:
                self.attn_pool = None
            self.global_pool = global_pool
        self.head = nn.Linear(self.embed_dim, num_classes) if num_classes > 0 else nn.Identity()

    def set_input_size(self, img_size=None, patch_size=None):
        """Update the input image resolution and patch size.

        Args:
            img_size: New input resolution, if None current resolution is used.
            patch_size: New patch size, if None existing patch size is used.
        """
        prev_grid_size = self.patch_embed.grid_size
        self.patch_embed.set_input_size(img_size=img_size, patch_size=patch_size)
        if self.pos_embed is not None:
            num_prefix_tokens = 0 if self.no_embed_class else self.num_prefix_tokens
            num_new_tokens = self.patch_embed.num_patches + num_prefix_tokens
            if num_new_tokens != self.pos_embed.shape[1]:
                self.pos_embed = nn.Parameter(resample_abs_pos_embed(self.pos_embed, new_size=self.patch_embed.grid_size, old_size=prev_grid_size, num_prefix_tokens=num_prefix_tokens, verbose=True))

    def _pos_embed(self, x):
        """Apply positional embedding to input."""
        if self.pos_embed is None:
            return x.view(x.shape[0], -1, x.shape[-1])
        if self.dynamic_img_size:
            B, H, W, C = x.shape
            prev_grid_size = self.patch_embed.grid_size
            pos_embed = resample_abs_pos_embed(self.pos_embed, new_size=(H, W), old_size=prev_grid_size, num_prefix_tokens=0 if self.no_embed_class else self.num_prefix_tokens)
            x = x.view(B, -1, C)
        else:
            pos_embed = self.pos_embed
        to_cat = []
        if self.cls_token is not None:
            to_cat.append(self.cls_token.expand(x.shape[0], -1, -1))
        if self.reg_token is not None:
            to_cat.append(self.reg_token.expand(x.shape[0], -1, -1))
        if self.no_embed_class:
            x = x + pos_embed
            if to_cat:
                x = torch.cat(to_cat + [x], dim=1)
        else:
            if to_cat:
                x = torch.cat(to_cat + [x], dim=1)
            x = x + pos_embed
        return self.pos_drop(x)

    def forward_intermediates(self, x, indices=None, return_prefix_tokens=False, norm=False, stop_early=False, output_fmt='NCHW', intermediates_only=False, output_dict=False, attn_mask=None):
        """ Forward features that returns intermediates.

        Args:
            x: Input image tensor
            indices: Take last n blocks if int, all if None, select matching indices if sequence
            return_prefix_tokens: Return both prefix and spatial intermediate tokens
            norm: Apply norm layer to all intermediates
            stop_early: Stop iterating over blocks when last desired intermediate hit
            output_fmt: Shape of intermediate feature outputs
            intermediates_only: Only return intermediate features
            output_dict: Return outputs as a dictionary with 'image_features' and 'image_intermediates' keys
            attn_mask: Optional attention mask for masked attention (e.g., for NaFlex)
        Returns:
            A tuple with (final_features, intermediates), a list of intermediate features, or a dictionary containing
            'image_features' and 'image_intermediates' (and optionally 'image_intermediates_prefix')
        """
        assert output_fmt in ('NCHW', 'NLC'), 'Output format must be one of NCHW or NLC.'
        reshape = output_fmt == 'NCHW'
        intermediates = []
        take_indices, max_index = feature_take_indices(len(self.blocks), indices)
        B, _, height, width = x.shape
        x = self.patch_embed(x)
        x = self._pos_embed(x)
        x = self.patch_drop(x)
        x = self.norm_pre(x)
        if torch.jit.is_scripting() or not stop_early:
            blocks = self.blocks
        else:
            blocks = self.blocks[:max_index + 1]
        for i, blk in enumerate(blocks):
            if attn_mask is not None:
                x = blk(x, attn_mask=attn_mask)
            elif self.grad_checkpointing and (not torch.jit.is_scripting()):
                x = checkpoint(blk, x)
            else:
                x = blk(x)
            if i in take_indices:
                intermediates.append(self.norm(x) if norm else x)
        if self.num_prefix_tokens:
            prefix_tokens = [y[:, 0:self.num_prefix_tokens] for y in intermediates]
            intermediates = [y[:, self.num_prefix_tokens:] for y in intermediates]
        else:
            prefix_tokens = None
        if reshape:
            H, W = self.patch_embed.dynamic_feat_size((height, width))
            intermediates = [y.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous() for y in intermediates]
        if output_dict:
            result_dict = {}
            result_dict['image_intermediates'] = intermediates
            if prefix_tokens is not None and return_prefix_tokens:
                result_dict['image_intermediates_prefix'] = prefix_tokens
            if not intermediates_only:
                x_final = self.norm(x)
                result_dict['image_features'] = x_final
            return result_dict
        if not torch.jit.is_scripting() and return_prefix_tokens and (prefix_tokens is not None):
            intermediates = list(zip(intermediates, prefix_tokens))
        if intermediates_only:
            return intermediates
        x = self.norm(x)
        return (x, intermediates)

    def prune_intermediate_layers(self, indices=1, prune_norm=False, prune_head=True):
        """Prune layers not required for specified intermediates.

        Args:
            indices: Indices of intermediate layers to keep.
            prune_norm: Whether to prune normalization layer.
            prune_head: Whether to prune the classifier head.

        Returns:
            List of indices that were kept.
        """
        take_indices, max_index = feature_take_indices(len(self.blocks), indices)
        self.blocks = self.blocks[:max_index + 1]
        if prune_norm:
            self.norm = nn.Identity()
        if prune_head:
            self.fc_norm = nn.Identity()
            self.reset_classifier(0, '')
        return take_indices

    def get_intermediate_layers(self, x, n=1, reshape=False, return_prefix_tokens=False, norm=False, attn_mask=None):
        """Get intermediate layer outputs (DINO interface compatibility).

        NOTE: This API is for backwards compat, favour using forward_intermediates() directly.

        Args:
            x: Input tensor.
            n: Number or indices of layers.
            reshape: Reshape to NCHW format.
            return_prefix_tokens: Return prefix tokens.
            norm: Apply normalization.

        Returns:
            List of intermediate features.
        """
        return self.forward_intermediates(x, n, return_prefix_tokens=return_prefix_tokens, norm=norm, output_fmt='NCHW' if reshape else 'NLC', intermediates_only=True, attn_mask=attn_mask)

    def forward_features(self, x, attn_mask=None):
        """Forward pass through feature layers (embeddings, transformer blocks, post-transformer norm)."""
        x = self.patch_embed(x)
        x = self._pos_embed(x)
        x = self.patch_drop(x)
        x = self.norm_pre(x)
        if attn_mask is not None:
            for blk in self.blocks:
                x = blk(x, attn_mask=attn_mask)
        elif self.grad_checkpointing and (not torch.jit.is_scripting()):
            x = checkpoint_seq(self.blocks, x)
        else:
            x = self.blocks(x)
        x = self.norm(x)
        return x

    def pool(self, x, pool_type=None):
        """Apply pooling to feature tokens.

        Args:
            x: Feature tensor.
            pool_type: Pooling type override.

        Returns:
            Pooled features.
        """
        if self.attn_pool is not None:
            if not self.pool_include_prefix:
                x = x[:, self.num_prefix_tokens:]
            x = self.attn_pool(x)
            return x
        pool_type = self.global_pool if pool_type is None else pool_type
        x = global_pool_nlc(x, pool_type=pool_type, num_prefix_tokens=self.num_prefix_tokens, reduce_include_prefix=self.pool_include_prefix)
        return x

    def forward_head(self, x, pre_logits=False):
        """Forward pass through classifier head.

        Args:
            x: Feature tensor.
            pre_logits: Return features before final classifier.

        Returns:
            Output tensor.
        """
        x = self.pool(x)
        x = self.fc_norm(x)
        x = self.head_drop(x)
        return x if pre_logits else self.head(x)

    def forward(self, x, attn_mask=None):
        x = self.forward_features(x, attn_mask=attn_mask)
        x = self.forward_head(x)
        return x

def init_weights_vit_timm(module, name=''):
    """ViT weight initialization, original timm impl (for reproducibility).

    Args:
        module: Module to initialize.
        name: Module name for context.
    """
    if isinstance(module, nn.Linear):
        trunc_normal_(module.weight, std=0.02)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
    elif hasattr(module, 'init_weights'):
        module.init_weights()

def init_weights_vit_jax(module, name='', head_bias=0.0):
    """ViT weight initialization, matching JAX (Flax) impl.

    Args:
        module: Module to initialize.
        name: Module name for context.
        head_bias: Bias value for head layer.
    """
    if isinstance(module, nn.Linear):
        if name.startswith('head'):
            nn.init.zeros_(module.weight)
            nn.init.constant_(module.bias, head_bias)
        else:
            nn.init.xavier_uniform_(module.weight)
            if module.bias is not None:
                nn.init.normal_(module.bias, std=1e-06) if 'mlp' in name else nn.init.zeros_(module.bias)
    elif isinstance(module, nn.Conv2d):
        lecun_normal_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
    elif hasattr(module, 'init_weights'):
        module.init_weights()

def init_weights_vit_moco(module, name=''):
    """ViT weight initialization, matching moco-v3 impl minus fixed PatchEmbed.

    Args:
        module: Module to initialize.
        name: Module name for context.
    """
    if isinstance(module, nn.Linear):
        if 'qkv' in name:
            val = math.sqrt(6.0 / float(module.weight.shape[0] // 3 + module.weight.shape[1]))
            nn.init.uniform_(module.weight, -val, val)
        else:
            nn.init.xavier_uniform_(module.weight)
        if module.bias is not None:
            nn.init.zeros_(module.bias)
    elif hasattr(module, 'init_weights'):
        module.init_weights()

def get_init_weights_vit(mode='jax', head_bias=0.0):
    if 'jax' in mode:
        return partial(init_weights_vit_jax, head_bias=head_bias)
    elif 'moco' in mode:
        return init_weights_vit_moco
    else:
        return init_weights_vit_timm

@torch.no_grad()
def _load_weights(model, checkpoint_path, prefix='', load_bfloat16=False):
    """ Load weights from .npz checkpoints for official Google Brain Flax implementation
    """
    import numpy as np
    if load_bfloat16:
        import jax.numpy as jnp
        import ml_dtypes

    def _n2p(_w, t=True, idx=None):
        if idx is not None:
            _w = _w[idx]
        if load_bfloat16:
            _w = _w.view(ml_dtypes.bfloat16).astype(jnp.float32)
            _w = np.array(_w)
        if _w.ndim == 4 and _w.shape[0] == _w.shape[1] == _w.shape[2] == 1:
            _w = _w.flatten()
        if t:
            if _w.ndim == 4:
                _w = _w.transpose([3, 2, 0, 1])
            elif _w.ndim == 3:
                _w = _w.transpose([2, 0, 1])
            elif _w.ndim == 2:
                _w = _w.transpose([1, 0])
        _w = torch.from_numpy(_w)
        return _w
    if load_bfloat16:
        w = jnp.load(checkpoint_path)
    else:
        w = np.load(checkpoint_path)
    interpolation = 'bilinear'
    antialias = False
    big_vision = False
    if not prefix:
        if 'opt/target/embedding/kernel' in w:
            prefix = 'opt/target/'
        elif 'params/embedding/kernel' in w:
            prefix = 'params/'
            big_vision = True
        elif 'params/img/embedding/kernel' in w:
            prefix = 'params/img/'
            big_vision = True
    if hasattr(model.patch_embed, 'backbone'):
        backbone = model.patch_embed.backbone
        stem_only = not hasattr(backbone, 'stem')
        stem = backbone if stem_only else backbone.stem
        stem.conv.weight.copy_(adapt_input_conv(stem.conv.weight.shape[1], _n2p(w['{0}conv_root/kernel'.format(prefix)])))
        stem.norm.weight.copy_(_n2p(w['{0}gn_root/scale'.format(prefix)]))
        stem.norm.bias.copy_(_n2p(w['{0}gn_root/bias'.format(prefix)]))
        if not stem_only:
            for i, stage in enumerate(backbone.stages):
                for j, block in enumerate(stage.blocks):
                    bp = '{0}block{1}/unit{2}/'.format(prefix, i + 1, j + 1)
                    for r in range(3):
                        getattr(block, 'conv{0}'.format(r + 1)).weight.copy_(_n2p(w['{0}conv{1}/kernel'.format(bp, r + 1)]))
                        getattr(block, 'norm{0}'.format(r + 1)).weight.copy_(_n2p(w['{0}gn{1}/scale'.format(bp, r + 1)]))
                        getattr(block, 'norm{0}'.format(r + 1)).bias.copy_(_n2p(w['{0}gn{1}/bias'.format(bp, r + 1)]))
                    if block.downsample is not None:
                        block.downsample.conv.weight.copy_(_n2p(w['{0}conv_proj/kernel'.format(bp)]))
                        block.downsample.norm.weight.copy_(_n2p(w['{0}gn_proj/scale'.format(bp)]))
                        block.downsample.norm.bias.copy_(_n2p(w['{0}gn_proj/bias'.format(bp)]))
        embed_conv_w = _n2p(w['{0}embedding/kernel'.format(prefix)])
    else:
        embed_conv_w = adapt_input_conv(model.patch_embed.proj.weight.shape[1], _n2p(w['{0}embedding/kernel'.format(prefix)]))
    if embed_conv_w.shape[-2:] != model.patch_embed.proj.weight.shape[-2:]:
        embed_conv_w = resample_patch_embed(embed_conv_w, model.patch_embed.proj.weight.shape[-2:], interpolation=interpolation, antialias=antialias, verbose=True)
    model.patch_embed.proj.weight.copy_(embed_conv_w)
    model.patch_embed.proj.bias.copy_(_n2p(w['{0}embedding/bias'.format(prefix)]))
    if model.cls_token is not None:
        model.cls_token.copy_(_n2p(w['{0}cls'.format(prefix)], t=False))
    if big_vision:
        pos_embed_w = _n2p(w['{0}pos_embedding'.format(prefix)], t=False)
    else:
        pos_embed_w = _n2p(w['{0}Transformer/posembed_input/pos_embedding'.format(prefix)], t=False)
    if pos_embed_w.shape != model.pos_embed.shape:
        num_prefix_tokens = 0 if getattr(model, 'no_embed_class', False) else getattr(model, 'num_prefix_tokens', 1)
        pos_embed_w = resample_abs_pos_embed(pos_embed_w, new_size=model.patch_embed.grid_size, num_prefix_tokens=num_prefix_tokens, interpolation=interpolation, antialias=antialias, verbose=True)
    model.pos_embed.copy_(pos_embed_w)
    model.norm.weight.copy_(_n2p(w['{0}Transformer/encoder_norm/scale'.format(prefix)]))
    model.norm.bias.copy_(_n2p(w['{0}Transformer/encoder_norm/bias'.format(prefix)]))
    if isinstance(model.head, nn.Linear) and '{0}head/bias'.format(prefix) in w and (model.head.bias.shape[0] == w['{0}head/bias'.format(prefix)].shape[-1]):
        model.head.weight.copy_(_n2p(w['{0}head/kernel'.format(prefix)]))
        model.head.bias.copy_(_n2p(w['{0}head/bias'.format(prefix)]))
    if model.attn_pool is not None:
        block_prefix = '{0}MAPHead_0/'.format(prefix)
        mha_prefix = block_prefix + 'MultiHeadDotProductAttention_0/'.format()
        model.attn_pool.latent.copy_(_n2p(w['{0}probe'.format(block_prefix)], t=False))
        model.attn_pool.kv.weight.copy_(torch.cat([_n2p(w['{0}{1}/kernel'.format(mha_prefix, n)], t=False).flatten(1).T for n in ('key', 'value')]))
        model.attn_pool.kv.bias.copy_(torch.cat([_n2p(w['{0}{1}/bias'.format(mha_prefix, n)], t=False).reshape(-1) for n in ('key', 'value')]))
        model.attn_pool.q.weight.copy_(_n2p(w['{0}query/kernel'.format(mha_prefix)], t=False).flatten(1).T)
        model.attn_pool.q.bias.copy_(_n2p(w['{0}query/bias'.format(mha_prefix)], t=False).reshape(-1))
        model.attn_pool.proj.weight.copy_(_n2p(w['{0}out/kernel'.format(mha_prefix)]).flatten(1))
        model.attn_pool.proj.bias.copy_(_n2p(w['{0}out/bias'.format(mha_prefix)]))
        model.attn_pool.norm.weight.copy_(_n2p(w['{0}LayerNorm_0/scale'.format(block_prefix)]))
        model.attn_pool.norm.bias.copy_(_n2p(w['{0}LayerNorm_0/bias'.format(block_prefix)]))
        for r in range(2):
            getattr(model.attn_pool.mlp, 'fc{0}'.format(r + 1)).weight.copy_(_n2p(w['{0}MlpBlock_0/Dense_{1}/kernel'.format(block_prefix, r)]))
            getattr(model.attn_pool.mlp, 'fc{0}'.format(r + 1)).bias.copy_(_n2p(w['{0}MlpBlock_0/Dense_{1}/bias'.format(block_prefix, r)]))
    mha_sub, b_sub, ln1_sub = (0, 0, 1) if big_vision else (1, 3, 2)
    for i, block in enumerate(model.blocks.children()):
        if '{0}Transformer/encoderblock/LayerNorm_0/scale'.format(prefix) in w:
            block_prefix = '{0}Transformer/encoderblock/'.format(prefix)
            idx = i
        else:
            block_prefix = '{0}Transformer/encoderblock_{1}/'.format(prefix, i)
            idx = None
        mha_prefix = block_prefix + 'MultiHeadDotProductAttention_{0}/'.format(mha_sub)
        block.norm1.weight.copy_(_n2p(w['{0}LayerNorm_0/scale'.format(block_prefix)], idx=idx))
        block.norm1.bias.copy_(_n2p(w['{0}LayerNorm_0/bias'.format(block_prefix)], idx=idx))
        block.attn.qkv.weight.copy_(torch.cat([_n2p(w['{0}{1}/kernel'.format(mha_prefix, n)], t=False, idx=idx).flatten(1).T for n in ('query', 'key', 'value')]))
        block.attn.qkv.bias.copy_(torch.cat([_n2p(w['{0}{1}/bias'.format(mha_prefix, n)], t=False, idx=idx).reshape(-1) for n in ('query', 'key', 'value')]))
        block.attn.proj.weight.copy_(_n2p(w['{0}out/kernel'.format(mha_prefix)], idx=idx).flatten(1))
        block.attn.proj.bias.copy_(_n2p(w['{0}out/bias'.format(mha_prefix)], idx=idx))
        block.norm2.weight.copy_(_n2p(w['{0}LayerNorm_{1}/scale'.format(block_prefix, ln1_sub)], idx=idx))
        block.norm2.bias.copy_(_n2p(w['{0}LayerNorm_{1}/bias'.format(block_prefix, ln1_sub)], idx=idx))
        for r in range(2):
            getattr(block.mlp, 'fc{0}'.format(r + 1)).weight.copy_(_n2p(w['{0}MlpBlock_{1}/Dense_{2}/kernel'.format(block_prefix, b_sub, r)], idx=idx))
            getattr(block.mlp, 'fc{0}'.format(r + 1)).bias.copy_(_n2p(w['{0}MlpBlock_{1}/Dense_{2}/bias'.format(block_prefix, b_sub, r)], idx=idx))

def _convert_openai_clip(state_dict, model, prefix='visual.'):
    out_dict = {}
    swaps = [('conv1', 'patch_embed.proj'), ('positional_embedding', 'pos_embed'), ('transformer.resblocks.', 'blocks.'), ('ln_pre', 'norm_pre'), ('ln_post', 'norm'), ('ln_', 'norm'), ('in_proj_', 'qkv.'), ('out_proj', 'proj'), ('mlp.c_fc', 'mlp.fc1'), ('mlp.c_proj', 'mlp.fc2')]
    for k, v in state_dict.items():
        if not k.startswith(prefix):
            continue
        k = k.replace(prefix, '')
        for sp in swaps:
            k = k.replace(sp[0], sp[1])
        if k == 'proj':
            k = 'head.weight'
            v = v.transpose(0, 1)
            out_dict['head.bias'] = torch.zeros(v.shape[0])
        elif k == 'class_embedding':
            k = 'cls_token'
            v = v.unsqueeze(0).unsqueeze(1)
        elif k == 'pos_embed':
            v = v.unsqueeze(0)
        out_dict[k] = v
    return out_dict

def _convert_dinov2(state_dict, model):
    import re
    out_dict = {}
    state_dict.pop('mask_token', None)
    if 'register_tokens' in state_dict:
        out_dict['reg_token'] = state_dict.pop('register_tokens')
        out_dict['cls_token'] = state_dict.pop('cls_token') + state_dict['pos_embed'][:, 0]
        out_dict['pos_embed'] = state_dict.pop('pos_embed')[:, 1:]
    for k, v in state_dict.items():
        if re.match('blocks\\.(\\d+)\\.mlp\\.w12\\.(?:weight|bias)', k):
            out_dict[k.replace('w12', 'fc1')] = v
            continue
        elif re.match('blocks\\.(\\d+)\\.mlp\\.w3\\.(?:weight|bias)', k):
            out_dict[k.replace('w3', 'fc2')] = v
            continue
        out_dict[k] = v
    return out_dict

def _convert_aimv2(state_dict, model):
    out_dict = {}
    for k, v in state_dict.items():
        k = k.replace('norm_1', 'norm1')
        k = k.replace('norm_2', 'norm2')
        k = k.replace('preprocessor.patchifier.', 'patch_embed.')
        k = k.replace('preprocessor.pos_embed', 'pos_embed')
        k = k.replace('trunk.', '')
        k = k.replace('post_trunk_norm.', 'norm.')
        k = k.replace('mlp.fc1', 'mlp.fc1_g')
        k = k.replace('mlp.fc3', 'mlp.fc1_x')
        out_dict[k] = v
    return out_dict

def _convert_beit3(state_dict, model):
    """
    Turn a BEiT-3 checkpoint into a standard VisionTransformer state-dict.
    """
    import re
    state_dict = state_dict.get('model', state_dict)
    for k in ('beit3.text_embed.weight', 'beit3.vision_embed.mask_token'):
        state_dict.pop(k, None)
    rules = [('beit3\\.', ''), ('vision_embed\\.cls_token', 'cls_token'), ('vision_embed\\.', 'patch_embed.'), ('embed_positions\\.', 'pos_embed.'), ('encoder\\.', ''), ('layers\\.', 'blocks.'), ('ffn_layernorm\\.', 'norm.'), ('ffn\\.', 'mlp.'), ('self_attn_layer_norm\\.', 'norm1.'), ('self_attn\\.', 'attn.'), ('final_layer_norm\\.', 'norm2.'), ('inner_attn_ln', 'norm'), ('out_proj', 'proj'), ('\\.A\\.', '.')]
    tmp = {}
    for k, v in state_dict.items():
        if '.B.' in k:
            continue
        for old, new in rules:
            k = re.sub(old, new, k)
        if k == 'pos_embed.weight':
            tmp['pos_embed'] = v[2:].unsqueeze(0)
        else:
            tmp[k] = v
    out, buf = ({}, {})
    pat = re.compile('blocks\\.(\\d+)\\.attn\\.(q|k|v)_proj\\.(weight|bias)$')
    for k, v in tmp.items():
        m = pat.fullmatch(k)
        if not m:
            out[k] = v
            continue
        blk, which, kind = m.groups()
        stash = buf.setdefault((blk, kind), {})
        stash[which] = v
        if len(stash) == 3:
            out['blocks.{0}.attn.qkv.{1}'.format(blk, kind)] = torch.cat([stash['q'], stash['k'], stash['v']], dim=0)
    return out

def checkpoint_filter_fn(state_dict, model, adapt_layer_scale=False, interpolation='bicubic', antialias=True):
    """ convert patch embedding weight from manual patchify + linear proj to conv"""
    import re
    out_dict = {}
    state_dict = state_dict.get('model', state_dict)
    state_dict = state_dict.get('state_dict', state_dict)
    prefix = ''
    if 'visual.class_embedding' in state_dict:
        state_dict = _convert_openai_clip(state_dict, model)
    elif 'module.visual.class_embedding' in state_dict:
        state_dict = _convert_openai_clip(state_dict, model, prefix='module.visual.')
    elif 'mask_token' in state_dict:
        state_dict = _convert_dinov2(state_dict, model)
    elif any(('beit3.' in k for k in state_dict.keys())):
        state_dict = _convert_beit3(state_dict, model)
    elif 'encoder' in state_dict:
        state_dict = state_dict['encoder']
        prefix = 'module.'
    elif 'visual.trunk.pos_embed' in state_dict or 'visual.trunk.blocks.0.norm1.weight' in state_dict:
        prefix = 'visual.trunk.'
        if 'visual.head.proj.weight' in state_dict and isinstance(model.head, nn.Linear):
            out_dict['head.weight'] = state_dict['visual.head.proj.weight']
            out_dict['head.bias'] = torch.zeros(state_dict['visual.head.proj.weight'].shape[0])
    elif 'module.visual.trunk.pos_embed' in state_dict:
        prefix = 'module.visual.trunk.'
    elif 'preprocessor.patchifier.proj.weight' in state_dict:
        state_dict = _convert_aimv2(state_dict, model)
    if prefix:
        state_dict = {k[len(prefix):]: v for k, v in state_dict.items() if k.startswith(prefix)}
    for k, v in state_dict.items():
        if 'patch_embed.proj.weight' in k:
            O, I, H, W = model.patch_embed.proj.weight.shape
            if len(v.shape) < 4:
                O, I, H, W = model.patch_embed.proj.weight.shape
                v = v.reshape(O, -1, H, W)
            if v.shape[-1] != W or v.shape[-2] != H:
                v = resample_patch_embed(v, (H, W), interpolation=interpolation, antialias=antialias, verbose=True)
        elif k == 'pos_embed' and v.shape[1] != model.pos_embed.shape[1]:
            num_prefix_tokens = 0 if getattr(model, 'no_embed_class', False) else getattr(model, 'num_prefix_tokens', 1)
            v = resample_abs_pos_embed(v, new_size=model.patch_embed.grid_size, num_prefix_tokens=num_prefix_tokens, interpolation=interpolation, antialias=antialias, verbose=True)
        elif adapt_layer_scale and 'gamma_' in k:
            k = re.sub('gamma_([0-9])', 'ls\\1.gamma', k)
        elif 'pre_logits' in k:
            continue
        out_dict[k] = v
    return out_dict
_USE_NAFLEX_DEFAULT = os.environ.get('TIMM_USE_NAFLEXVIT', 'false').lower() == 'true'

def _create_vision_transformer(variant, pretrained=False, use_naflex=None, **kwargs):
    if use_naflex is None:
        use_naflex = _USE_NAFLEX_DEFAULT
    if use_naflex:
        from .naflexvit import _create_naflexvit_from_classic
        return _create_naflexvit_from_classic(variant, pretrained, **kwargs)
    out_indices = kwargs.pop('out_indices', 3)
    if 'flexi' in variant:
        _filter_fn = partial(checkpoint_filter_fn, interpolation='bilinear', antialias=False)
    else:
        _filter_fn = checkpoint_filter_fn
    strict = kwargs.pop('pretrained_strict', True)
    if 'siglip' in variant and kwargs.get('global_pool', None) != 'map':
        strict = False
    return build_model_with_cfg(VisionTransformer, variant, pretrained, pretrained_filter_fn=_filter_fn, pretrained_strict=strict, feature_cfg=dict(out_indices=out_indices, feature_cls='getter'), **kwargs)

@register_model
def vit_small_patch16_224(pretrained=False, **kwargs):
    """ ViT-Small (ViT-S/16)
    """
    model_args = dict(patch_size=16, embed_dim=384, depth=12, num_heads=6)
    model = _create_vision_transformer('vit_small_patch16_224', pretrained=pretrained, **dict(model_args, **kwargs))
    return model

@register_model
def vit_giant_patch14_224(pretrained=False, **kwargs):
    """ ViT-Giant (little-g) model (ViT-g/14) from `Scaling Vision Transformers` - https://arxiv.org/abs/2106.04560
    """
    model_args = dict(patch_size=14, embed_dim=1408, mlp_ratio=48 / 11, depth=40, num_heads=16)
    model = _create_vision_transformer('vit_giant_patch14_224', pretrained=pretrained, **dict(model_args, **kwargs))
    return model

@register_model
def vit_base_patch14_dinov2(pretrained=False, **kwargs):
    """ ViT-B/14 for DINOv2
    """
    model_args = dict(patch_size=14, embed_dim=768, depth=12, num_heads=12, init_values=1e-05)
    model = _create_vision_transformer('vit_base_patch14_dinov2', pretrained=pretrained, **dict(model_args, **kwargs))
    return model

@register_model
def vit_base_patch16_siglip_256(pretrained=False, **kwargs):
    model_args = dict(patch_size=16, embed_dim=768, depth=12, num_heads=12, class_token=False, global_pool='map')
    model = _create_vision_transformer('vit_base_patch16_siglip_256', pretrained=pretrained, **dict(model_args, **kwargs))
    return model
