"""transformers, as far as the ported modeling files reach, for the eval
forward the PyTorch 2 dashboard runs.

Two kinds of module live here.  Files whose header says "Generated by
benchmark/suites/port.py" are upstream transformers source through the
porter's syntax-only rewrites.  Every other file is a hand-written stand-in
for upstream code that has no Python 2 form (dataclass outputs, the config
machinery, ContextVar-based output capture); each mirrors the upstream
function on the path an eval forward takes and raises NotImplementedError on
any other path.  Environment queries (torch version, available devices)
answer as the reference torch run answers them, so the ported code takes
the branch the reference took.
"""
__version__ = "5.13.0"
