# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from the dataclass fields of
# transformers.modeling_outputs (transformers 5.13.0, source sha256 ae482f69cb3c393a).
"""The ModelOutput classes of transformers.modeling_outputs.  Upstream they
are dataclasses over an OrderedDict; here each lists its fields in the
order upstream declares them (generated below from the dataclass fields),
and indexing, to_tuple() and iteration skip the fields left None, as
upstream's do."""


class ModelOutput(object):
    _fields = ()

    def __init__(self, *args, **kwargs):
        # each field written exactly once: writing an attribute a second time
        # flips the JIT's per-attribute "ever mutated" assumption and throws
        # away every trace that relied on it
        for k in kwargs:
            if k not in self._fields:
                raise TypeError("%s has no field %s"
                                % (type(self).__name__, k))
        for i, f in enumerate(self._fields):
            setattr(self, f, args[i] if i < len(args) else kwargs.get(f))

    def keys(self):
        return [f for f in self._fields if getattr(self, f) is not None]

    def to_tuple(self):
        return tuple(getattr(self, f) for f in self.keys())

    def __getitem__(self, k):
        if isinstance(k, str):
            return getattr(self, k)
        return self.to_tuple()[k]

    def __setitem__(self, k, v):
        setattr(self, k, v)

    def __iter__(self):
        return iter(self.keys())

    def __len__(self):
        return len(self.keys())


def _output(name, fields):
    return type(name, (ModelOutput,), {"_fields": tuple(fields)})


BackboneOutput = _output('BackboneOutput', ['feature_maps', 'hidden_states', 'attentions'])
BaseModelOutput = _output('BaseModelOutput', ['last_hidden_state', 'hidden_states', 'attentions'])
BaseModelOutputWithCrossAttentions = _output('BaseModelOutputWithCrossAttentions', ['last_hidden_state', 'hidden_states', 'attentions', 'cross_attentions'])
BaseModelOutputWithNoAttention = _output('BaseModelOutputWithNoAttention', ['last_hidden_state', 'hidden_states'])
BaseModelOutputWithPast = _output('BaseModelOutputWithPast', ['last_hidden_state', 'past_key_values', 'hidden_states', 'attentions'])
BaseModelOutputWithPastAndCrossAttentions = _output('BaseModelOutputWithPastAndCrossAttentions', ['last_hidden_state', 'past_key_values', 'hidden_states', 'attentions', 'cross_attentions'])
BaseModelOutputWithPooling = _output('BaseModelOutputWithPooling', ['last_hidden_state', 'pooler_output', 'hidden_states', 'attentions'])
BaseModelOutputWithPoolingAndCrossAttentions = _output('BaseModelOutputWithPoolingAndCrossAttentions', ['last_hidden_state', 'pooler_output', 'hidden_states', 'past_key_values', 'attentions', 'cross_attentions'])
BaseModelOutputWithPoolingAndNoAttention = _output('BaseModelOutputWithPoolingAndNoAttention', ['last_hidden_state', 'pooler_output', 'hidden_states'])
BaseModelOutputWithPoolingAndProjection = _output('BaseModelOutputWithPoolingAndProjection', ['last_hidden_state', 'pooler_output', 'hidden_states', 'attentions', 'projection_state'])
CausalLMOutput = _output('CausalLMOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
CausalLMOutputWithCrossAttentions = _output('CausalLMOutputWithCrossAttentions', ['loss', 'logits', 'past_key_values', 'hidden_states', 'attentions', 'cross_attentions'])
CausalLMOutputWithPast = _output('CausalLMOutputWithPast', ['loss', 'logits', 'past_key_values', 'hidden_states', 'attentions'])
DepthEstimatorOutput = _output('DepthEstimatorOutput', ['loss', 'predicted_depth', 'hidden_states', 'attentions'])
ImageClassifierOutput = _output('ImageClassifierOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
ImageClassifierOutputWithNoAttention = _output('ImageClassifierOutputWithNoAttention', ['loss', 'logits', 'hidden_states'])
ImageSuperResolutionOutput = _output('ImageSuperResolutionOutput', ['loss', 'reconstruction', 'hidden_states', 'attentions'])
MaskedImageModelingOutput = _output('MaskedImageModelingOutput', ['loss', 'reconstruction', 'hidden_states', 'attentions'])
MaskedLMOutput = _output('MaskedLMOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
MoECausalLMOutputWithPast = _output('MoECausalLMOutputWithPast', ['loss', 'aux_loss', 'logits', 'past_key_values', 'hidden_states', 'attentions', 'router_logits'])
MoEModelOutput = _output('MoEModelOutput', ['last_hidden_state', 'hidden_states', 'attentions', 'router_probs', 'router_logits'])
MoEModelOutputWithPastAndCrossAttentions = _output('MoEModelOutputWithPastAndCrossAttentions', ['last_hidden_state', 'past_key_values', 'hidden_states', 'attentions', 'cross_attentions', 'router_probs', 'router_logits'])
MoeCausalLMOutputWithPast = _output('MoeCausalLMOutputWithPast', ['loss', 'aux_loss', 'logits', 'past_key_values', 'hidden_states', 'attentions', 'router_logits'])
MoeModelOutputWithPast = _output('MoeModelOutputWithPast', ['last_hidden_state', 'past_key_values', 'hidden_states', 'attentions', 'router_logits'])
MultipleChoiceModelOutput = _output('MultipleChoiceModelOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
NextSentencePredictorOutput = _output('NextSentencePredictorOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
QuestionAnsweringModelOutput = _output('QuestionAnsweringModelOutput', ['loss', 'start_logits', 'end_logits', 'hidden_states', 'attentions'])
SampleTSPredictionOutput = _output('SampleTSPredictionOutput', ['sequences'])
SemanticSegmenterOutput = _output('SemanticSegmenterOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
Seq2SeqLMOutput = _output('Seq2SeqLMOutput', ['loss', 'logits', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions'])
Seq2SeqMoEModelOutput = _output('Seq2SeqMoEModelOutput', ['last_hidden_state', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'decoder_router_logits', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions', 'encoder_router_logits'])
Seq2SeqMoEOutput = _output('Seq2SeqMoEOutput', ['loss', 'logits', 'encoder_z_loss', 'decoder_z_loss', 'encoder_aux_loss', 'decoder_aux_loss', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'decoder_router_logits', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions', 'encoder_router_logits'])
Seq2SeqModelOutput = _output('Seq2SeqModelOutput', ['last_hidden_state', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions'])
Seq2SeqQuestionAnsweringModelOutput = _output('Seq2SeqQuestionAnsweringModelOutput', ['loss', 'start_logits', 'end_logits', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions'])
Seq2SeqSequenceClassifierOutput = _output('Seq2SeqSequenceClassifierOutput', ['loss', 'logits', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions'])
Seq2SeqSpectrogramOutput = _output('Seq2SeqSpectrogramOutput', ['loss', 'spectrogram', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions'])
Seq2SeqTSModelOutput = _output('Seq2SeqTSModelOutput', ['last_hidden_state', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions', 'loc', 'scale', 'static_features'])
Seq2SeqTSPredictionOutput = _output('Seq2SeqTSPredictionOutput', ['loss', 'params', 'past_key_values', 'decoder_hidden_states', 'decoder_attentions', 'cross_attentions', 'encoder_last_hidden_state', 'encoder_hidden_states', 'encoder_attentions', 'loc', 'scale', 'static_features'])
SequenceClassifierOutput = _output('SequenceClassifierOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
SequenceClassifierOutputWithPast = _output('SequenceClassifierOutputWithPast', ['loss', 'logits', 'past_key_values', 'hidden_states', 'attentions'])
TokenClassifierOutput = _output('TokenClassifierOutput', ['loss', 'logits', 'hidden_states', 'attentions'])
Wav2Vec2BaseModelOutput = _output('Wav2Vec2BaseModelOutput', ['last_hidden_state', 'extract_features', 'hidden_states', 'attentions'])
XVectorOutput = _output('XVectorOutput', ['loss', 'logits', 'embeddings', 'hidden_states', 'attentions'])
