# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from transformers.pytorch_utils
# (transformers 5.13.0, source sha256 1d1ae097d2c9b4a1).  Do not edit; change the spec.
# Kept: apply_chunking_to_forward
#   inspect supplied for Python 2
from __future__ import absolute_import, division, print_function
import torch

class _Signature(object):
    def __init__(self, parameters):
        self.parameters = parameters


class inspect(object):
    """inspect.signature(f).parameters, counted as Python 3 counts them:
    a bound method's self is not a parameter.  Memoised per function, as
    a signature never changes."""
    _memo = {}

    @staticmethod
    def signature(f):
        fn = getattr(f, "__func__", f)
        bound = getattr(f, "__self__", None) is not None
        key = (fn, bound)
        sig = inspect._memo.get(key)
        if sig is None:
            import inspect as _inspect
            spec = _inspect.getargspec(fn)
            names = list(spec.args)[1 if bound else 0:]
            if spec.varargs:
                names.append(spec.varargs)
            if spec.keywords:
                names.append(spec.keywords)
            sig = inspect._memo[key] = _Signature(tuple(names))
        return sig


def apply_chunking_to_forward(forward_fn, chunk_size, chunk_dim, *input_tensors):
    """
    This function chunks the `input_tensors` into smaller input tensor parts of size `chunk_size` over the dimension
    `chunk_dim`. It then applies a layer `forward_fn` to each chunk independently to save memory.

    If the `forward_fn` is independent across the `chunk_dim` this function will yield the same result as directly
    applying `forward_fn` to `input_tensors`.

    Args:
        forward_fn (`Callable[..., torch.Tensor]`):
            The forward function of the model.
        chunk_size (`int`):
            The chunk size of a chunked tensor: `num_chunks = len(input_tensors[0]) / chunk_size`.
        chunk_dim (`int`):
            The dimension over which the `input_tensors` should be chunked.
        input_tensors (`tuple[torch.Tensor]`):
            The input tensors of `forward_fn` which will be chunked

    Returns:
        `torch.Tensor`: A tensor with the same shape as the `forward_fn` would have given if applied`.


    Examples:

    ```python
    # rename the usual forward() fn to forward_chunk()
    def forward_chunk(self, hidden_states):
        hidden_states = self.decoder(hidden_states)
        return hidden_states


    # implement a chunked forward function
    def forward(self, hidden_states):
        return apply_chunking_to_forward(self.forward_chunk, self.chunk_size_lm_head, self.seq_len_dim, hidden_states)
    ```"""
    assert len(input_tensors) > 0, '{0} has to be a tuple/list of tensors'.format(input_tensors)
    num_args_in_forward_chunk_fn = len(inspect.signature(forward_fn).parameters)
    if num_args_in_forward_chunk_fn != len(input_tensors):
        raise ValueError('forward_chunk_fn expects {0} arguments, but only {1} input tensors are given'.format(num_args_in_forward_chunk_fn, len(input_tensors)))
    if chunk_size > 0:
        tensor_shape = input_tensors[0].shape[chunk_dim]
        for input_tensor in input_tensors:
            if input_tensor.shape[chunk_dim] != tensor_shape:
                raise ValueError('All input tenors have to be of the same shape: {0}, found shape {1}'.format(tensor_shape, input_tensor.shape[chunk_dim]))
        if input_tensors[0].shape[chunk_dim] % chunk_size != 0:
            raise ValueError('The dimension to be chunked {0} has to be a multiple of the chunk size {1}'.format(input_tensors[0].shape[chunk_dim], chunk_size))
        num_chunks = input_tensors[0].shape[chunk_dim] // chunk_size
        input_tensors_chunks = tuple((input_tensor.chunk(num_chunks, dim=chunk_dim) for input_tensor in input_tensors))
        output_chunks = tuple((forward_fn(*input_tensors_chunk) for input_tensors_chunk in zip(*input_tensors_chunks)))
        return torch.cat(output_chunks, dim=chunk_dim)
    return forward_fn(*input_tensors)
