# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from torchvision.models._utils
# (torchvision 0.29.0+cu130, source sha256 972289ecdb2b81d2).  Do not edit; change the spec.
# Kept: _make_divisible
from __future__ import absolute_import, division, print_function
def _make_divisible(v, divisor, min_value=None):
    """
    This function is taken from the original tf repo.
    It ensures that all layers have a channel number that is divisible by 8
    It can be seen here:
    https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet/mobilenet.py
    """
    if min_value is None:
        min_value = divisor
    new_v = max(min_value, int(v + divisor / 2) // divisor * divisor)
    if new_v < 0.9 * v:
        new_v += divisor
    return new_v
