# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.activations
# (timm 1.0.22, source sha256 effc50cc017066d6).  Do not edit; change the spec.
# Kept: swish, Swish, mish, Mish, sigmoid, Sigmoid, tanh, Tanh, hard_swish, HardSwish, hard_sigmoid, HardSigmoid, hard_mish, HardMish, PReLU, gelu, GELU, gelu_tanh, GELUTanh, quick_gelu, QuickGELU
from __future__ import absolute_import, division, print_function
import torch
from torch import nn as nn
from torch.nn import functional as F

def swish(x, inplace=False):
    """Swish - Described in: https://arxiv.org/abs/1710.05941
    """
    return x.mul_(x.sigmoid()) if inplace else x.mul(x.sigmoid())

class Swish(nn.Module):

    def __init__(self, inplace=False):
        super(Swish, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return swish(x, self.inplace)

def mish(x, inplace=False):
    """Mish: A Self Regularized Non-Monotonic Neural Activation Function - https://arxiv.org/abs/1908.08681
    NOTE: I don't have a working inplace variant
    """
    return x.mul(F.softplus(x).tanh())

class Mish(nn.Module):
    """Mish: A Self Regularized Non-Monotonic Neural Activation Function - https://arxiv.org/abs/1908.08681
    """

    def __init__(self, inplace=False):
        super(Mish, self).__init__()

    def forward(self, x):
        return mish(x)

def sigmoid(x, inplace=False):
    return x.sigmoid_() if inplace else x.sigmoid()

class Sigmoid(nn.Module):

    def __init__(self, inplace=False):
        super(Sigmoid, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return x.sigmoid_() if self.inplace else x.sigmoid()

def tanh(x, inplace=False):
    return x.tanh_() if inplace else x.tanh()

class Tanh(nn.Module):

    def __init__(self, inplace=False):
        super(Tanh, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return x.tanh_() if self.inplace else x.tanh()

def hard_swish(x, inplace=False):
    inner = F.relu6(x + 3.0).div_(6.0)
    return x.mul_(inner) if inplace else x.mul(inner)

class HardSwish(nn.Module):

    def __init__(self, inplace=False):
        super(HardSwish, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return hard_swish(x, self.inplace)

def hard_sigmoid(x, inplace=False):
    if inplace:
        return x.add_(3.0).clamp_(0.0, 6.0).div_(6.0)
    else:
        return F.relu6(x + 3.0) / 6.0

class HardSigmoid(nn.Module):

    def __init__(self, inplace=False):
        super(HardSigmoid, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return hard_sigmoid(x, self.inplace)

def hard_mish(x, inplace=False):
    """ Hard Mish
    Experimental, based on notes by Mish author Diganta Misra at
      https://github.com/digantamisra98/H-Mish/blob/0da20d4bc58e696b6803f2523c58d3c8a82782d0/README.md
    """
    if inplace:
        return x.mul_(0.5 * (x + 2).clamp(min=0, max=2))
    else:
        return 0.5 * x * (x + 2).clamp(min=0, max=2)

class HardMish(nn.Module):

    def __init__(self, inplace=False):
        super(HardMish, self).__init__()
        self.inplace = inplace

    def forward(self, x):
        return hard_mish(x, self.inplace)

class PReLU(nn.PReLU):
    """Applies PReLU (w/ dummy inplace arg)
    """

    def __init__(self, num_parameters=1, init=0.25, inplace=False):
        super(PReLU, self).__init__(num_parameters=num_parameters, init=init)

    def forward(self, input):
        return F.prelu(input, self.weight)

def gelu(x, inplace=False):
    return F.gelu(x)

class GELU(nn.Module):
    """Applies the Gaussian Error Linear Units function (w/ dummy inplace arg)
    """

    def __init__(self, inplace=False):
        super(GELU, self).__init__()

    def forward(self, input):
        return F.gelu(input)

def gelu_tanh(x, inplace=False):
    return F.gelu(x, approximate='tanh')

class GELUTanh(nn.Module):
    """Applies the Gaussian Error Linear Units function (w/ dummy inplace arg)
    """

    def __init__(self, inplace=False):
        super(GELUTanh, self).__init__()

    def forward(self, input):
        return F.gelu(input, approximate='tanh')

def quick_gelu(x, inplace=False):
    return x * torch.sigmoid(1.702 * x)

class QuickGELU(nn.Module):
    """Applies the Gaussian Error Linear Units function (w/ dummy inplace arg)
    """

    def __init__(self, inplace=False):
        super(QuickGELU, self).__init__()

    def forward(self, input):
        return quick_gelu(input)
