# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.blur_pool
# (timm 1.0.22, source sha256 0bf29c58681cd478).  Do not edit; change the spec.
# Kept: BlurPool2d, create_aa
#   math.comb supplied for Python 2
from __future__ import absolute_import, division, print_function
from functools import partial
import torch
import torch.nn as nn
import torch.nn.functional as F
from timm.layers.padding import get_padding

def comb(n, k):
    """math.comb: the binomial coefficient, 0 for k > n."""
    if k < 0 or k > n:
        return 0
    r = 1
    for i in range(min(k, n - k)):
        r = r * (n - i) // (i + 1)
    return r


class BlurPool2d(nn.Module):
    """Creates a module that computes blurs and downsample a given feature map.
    See :cite:`zhang2019shiftinvar` for more details.
    Corresponds to the Downsample class, which does blurring and subsampling

    Args:
        channels = Number of input channels
        filt_size (int): binomial filter size for blurring. currently supports 3 (default) and 5.
        stride (int): downsampling filter stride

    Returns:
        torch.Tensor: the transformed tensor.
    """

    def __init__(self, channels=None, filt_size=3, stride=2, pad_mode='reflect', device=None, dtype=None):
        super(BlurPool2d, self).__init__()
        assert filt_size > 1
        self.channels = channels
        self.filt_size = filt_size
        self.stride = stride
        self.pad_mode = pad_mode
        self.padding = [get_padding(filt_size, stride, dilation=1)] * 4
        coeffs = torch.tensor([comb(filt_size - 1, k) for k in range(filt_size)], device='cpu', dtype=torch.float32) / 2 ** (filt_size - 1)
        blur_filter = (coeffs[:, None] * coeffs[None, :])[None, None, :, :]
        if channels is not None:
            blur_filter = blur_filter.repeat(self.channels, 1, 1, 1)
        self.register_buffer('filt', blur_filter.to(device=device, dtype=dtype), persistent=False)

    def forward(self, x):
        x = F.pad(x, self.padding, mode=self.pad_mode)
        if self.channels is None:
            channels = x.shape[1]
            weight = self.filt.expand(channels, 1, self.filt_size, self.filt_size)
        else:
            channels = self.channels
            weight = self.filt
        return F.conv2d(x, weight, stride=self.stride, groups=channels)

def _normalize_aa_layer(aa_layer):
    """Map string shorthands to callables (class or partial)."""
    if isinstance(aa_layer, str):
        key = aa_layer.lower().replace('_', '').replace('-', '')
        if key in ('avg', 'avgpool'):
            return nn.AvgPool2d
        if key in ('blur', 'blurpool'):
            return BlurPool2d
        if key == 'blurpc':
            return partial(BlurPool2d, pad_mode='constant')
        raise AssertionError('Unknown anti-aliasing layer ({0}).'.format(aa_layer))
    return aa_layer

def _underlying_cls(layer_callable):
    """Return the class behind a callable (unwrap partial), else None."""
    if isinstance(layer_callable, partial):
        return layer_callable.func
    return layer_callable if isinstance(layer_callable, type) else None

def _is_blurpool(layer_callable):
    """True if callable is BlurPool2d or a partial of it."""
    cls = _underlying_cls(layer_callable)
    try:
        return issubclass(cls, BlurPool2d)
    except TypeError:
        return False
    except Exception:
        return False

def create_aa(aa_layer, channels=None, stride=2, enable=True, noop=nn.Identity, device=None, dtype=None):
    """ Anti-aliasing factory that supports strings, classes, and partials. """
    if not aa_layer or not enable:
        return noop() if noop is not None else None
    aa_layer = _normalize_aa_layer(aa_layer)
    call_kwargs = {'channels': channels, 'stride': stride}
    if _is_blurpool(aa_layer):
        existing_kw = aa_layer.keywords if isinstance(aa_layer, partial) and aa_layer.keywords else {}
        if 'device' not in existing_kw and device is not None:
            call_kwargs['device'] = device
        if 'dtype' not in existing_kw and dtype is not None:
            call_kwargs['dtype'] = dtype
    try:
        return aa_layer(**call_kwargs)
    except TypeError:
        return aa_layer(stride)
