# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.conv_bn_act
# (timm 1.0.22, source sha256 4855d97df31fb588).  Do not edit; change the spec.
# Kept: ConvNormAct, ConvNormActAa, ConvBnAct
from __future__ import absolute_import, division, print_function
from torch import nn as nn
from timm.layers.blur_pool import create_aa
from timm.layers.create_conv2d import create_conv2d
from timm.layers.create_norm_act import get_norm_act_layer

class ConvNormAct(nn.Module):

    def __init__(self, in_channels, out_channels, kernel_size=1, stride=1, padding='', dilation=1, groups=1, bias=False, apply_norm=True, apply_act=True, norm_layer=nn.BatchNorm2d, act_layer=nn.ReLU, aa_layer=None, drop_layer=None, conv_kwargs=None, norm_kwargs=None, act_kwargs=None, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(ConvNormAct, self).__init__()
        conv_kwargs = dict(list(dd.items()) + list((conv_kwargs or {}).items()))
        norm_kwargs = dict(list(dd.items()) + list((norm_kwargs or {}).items()))
        act_kwargs = act_kwargs or {}
        use_aa = aa_layer is not None and stride > 1
        self.conv = create_conv2d(in_channels, out_channels, kernel_size, stride=1 if use_aa else stride, padding=padding, dilation=dilation, groups=groups, bias=bias, **conv_kwargs)
        if apply_norm:
            norm_act_layer = get_norm_act_layer(norm_layer, act_layer)
            if drop_layer:
                norm_kwargs['drop_layer'] = drop_layer
            self.bn = norm_act_layer(out_channels, apply_act=apply_act, act_kwargs=act_kwargs, **norm_kwargs)
        else:
            self.bn = nn.Sequential()
            if drop_layer:
                norm_kwargs['drop_layer'] = drop_layer
                self.bn.add_module('drop', drop_layer())
        self.aa = create_aa(aa_layer, out_channels, stride=stride, enable=use_aa, noop=None, **dd)

    @property
    def in_channels(self):
        return self.conv.in_channels

    @property
    def out_channels(self):
        return self.conv.out_channels

    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        aa = getattr(self, 'aa', None)
        if aa is not None:
            x = self.aa(x)
        return x
ConvBnAct = ConvNormAct
ConvNormActAa = ConvNormAct
