# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.fast_norm
# (timm 1.0.22, source sha256 728fdd004ed94434).  Do not edit; change the spec.
# Kept: is_fast_norm, fast_group_norm, fast_layer_norm, fast_rms_norm, rms_norm, rms_norm2d, fast_rms_norm2d, fast_simple_norm, simple_norm
#   fused_layer_norm_affine left unbound: bound by upstream's top-level try-import of apex, read on the fast-norm path only, which is off (_USE_FAST_NORM = False)
#   fused_rms_norm left unbound: bound by upstream's top-level try-import of apex, read on the fast-norm path only, which is off (_USE_FAST_NORM = False)
#   fused_rms_norm_affine left unbound: bound by upstream's top-level try-import of apex, read on the fast-norm path only, which is off (_USE_FAST_NORM = False)
#   has_apex left unbound: bound by upstream's top-level try-import of apex, read on the fast-norm path only, which is off (_USE_FAST_NORM = False)
#   has_apex_rmsnorm left unbound: bound by upstream's top-level try-import of apex, read on the fast-norm path only, which is off (_USE_FAST_NORM = False)
from __future__ import absolute_import, division, print_function
import torch
from torch.nn import functional as F
has_torch_rms_norm = hasattr(F, 'rms_norm')
_USE_FAST_NORM = False

def get_autocast_dtype(device='cuda'):
    try:
        return torch.get_autocast_dtype(device)
    except (AttributeError, TypeError):
        if device == 'cpu':
            return torch.get_autocast_cpu_dtype()
        else:
            assert device == 'cuda'
            return torch.get_autocast_gpu_dtype()

def is_autocast_enabled(device='cuda'):
    try:
        return torch.is_autocast_enabled(device)
    except TypeError:
        if device == 'cpu':
            return torch.is_autocast_cpu_enabled()
        else:
            assert device == 'cuda'
            return torch.is_autocast_enabled()

def is_fast_norm():
    return _USE_FAST_NORM

def fast_group_norm(x, num_groups, weight=None, bias=None, eps=1e-05):
    if torch.jit.is_scripting():
        return F.group_norm(x, num_groups, weight, bias, eps)
    if is_autocast_enabled(x.device.type):
        dt = get_autocast_dtype(x.device.type)
        x, weight, bias = (x.to(dt), weight.to(dt), bias.to(dt) if bias is not None else None)
    with torch.amp.autocast(device_type=x.device.type, enabled=False):
        return F.group_norm(x, num_groups, weight, bias, eps)

def fast_layer_norm(x, normalized_shape, weight=None, bias=None, eps=1e-05):
    if torch.jit.is_scripting():
        return F.layer_norm(x, normalized_shape, weight, bias, eps)
    if has_apex:
        return fused_layer_norm_affine(x, weight, bias, normalized_shape, eps)
    if is_autocast_enabled(x.device.type):
        dt = get_autocast_dtype(x.device.type)
        x, weight, bias = (x.to(dt), weight.to(dt), bias.to(dt) if bias is not None else None)
    with torch.amp.autocast(device_type=x.device.type, enabled=False):
        return F.layer_norm(x, normalized_shape, weight, bias, eps)

def rms_norm(x, normalized_shape, weight=None, eps=1e-05):
    norm_ndim = len(normalized_shape)
    v = x.pow(2)
    if torch.jit.is_scripting():
        assert norm_ndim == 1
        v = torch.mean(v, dim=-1).unsqueeze(-1)
    else:
        dims = tuple(range(-1, -norm_ndim - 1, -1))
        v = torch.mean(v, dim=dims, keepdim=True)
    x = x * torch.rsqrt(v + eps)
    if weight is not None:
        x = x * weight
    return x

def fast_rms_norm(x, normalized_shape, weight=None, eps=1e-05):
    if torch.jit.is_scripting():
        return rms_norm(x, normalized_shape, weight, eps)
    if has_apex_rmsnorm:
        if weight is None:
            return fused_rms_norm(x, normalized_shape, eps)
        else:
            return fused_rms_norm_affine(x, weight, normalized_shape, eps)
    if is_autocast_enabled(x.device.type):
        dt = get_autocast_dtype(x.device.type)
        x, weight = (x.to(dt), weight.to(dt))
    with torch.amp.autocast(device_type=x.device.type, enabled=False):
        if has_torch_rms_norm:
            x = F.rms_norm(x, normalized_shape, weight, eps)
        else:
            x = rms_norm(x, normalized_shape, weight, eps)
    return x

def rms_norm2d(x, normalized_shape, weight=None, eps=1e-05):
    assert len(normalized_shape) == 1
    v = x.pow(2)
    v = torch.mean(v, dim=1, keepdim=True)
    x = x * torch.rsqrt(v + eps)
    if weight is not None:
        x = x * weight.reshape(1, -1, 1, 1)
    return x

def fast_rms_norm2d(x, normalized_shape, weight=None, eps=1e-05):
    if torch.jit.is_scripting():
        return rms_norm2d(x, normalized_shape, weight, eps)
    if has_apex_rmsnorm:
        x = x.permute(0, 2, 3, 1)
        if weight is None:
            x = fused_rms_norm(x, normalized_shape, eps)
        else:
            x = fused_rms_norm_affine(x, weight, normalized_shape, eps)
        x = x.permute(0, 3, 1, 2)
    if is_autocast_enabled(x.device.type):
        dt = get_autocast_dtype(x.device.type)
        x, weight = (x.to(dt), weight.to(dt))
    with torch.amp.autocast(device_type=x.device.type, enabled=False):
        x = rms_norm2d(x, normalized_shape, weight, eps)
    return x

def simple_norm(x, normalized_shape, weight=None, eps=1e-05):
    norm_ndim = len(normalized_shape)
    if torch.jit.is_scripting():
        assert norm_ndim == 1
        v = torch.var(x, dim=-1).unsqueeze(-1)
    else:
        dims = tuple(range(-1, -norm_ndim - 1, -1))
        v = torch.var(x, dim=dims, keepdim=True)
    x = x * torch.rsqrt(v + eps)
    if weight is not None:
        x = x * weight
    return x

def fast_simple_norm(x, normalized_shape, weight=None, eps=1e-05):
    if torch.jit.is_scripting():
        return simple_norm(x, normalized_shape, weight, eps)
    if is_autocast_enabled(x.device.type):
        dt = get_autocast_dtype(x.device.type)
        x, weight = (x.to(dt), weight.to(dt))
    with torch.amp.autocast(device_type=x.device.type, enabled=False):
        x = simple_norm(x, normalized_shape, weight, eps)
    return x
