# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.grn
# (timm 1.0.22, source sha256 7a357b2a2f53c549).  Do not edit; change the spec.
# Kept: GlobalResponseNorm
from __future__ import absolute_import, division, print_function
import torch
from torch import nn as nn

class GlobalResponseNorm(nn.Module):
    """ Global Response Normalization layer
    """

    def __init__(self, dim, eps=1e-06, channels_last=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(GlobalResponseNorm, self).__init__()
        self.eps = eps
        if channels_last:
            self.spatial_dim = (1, 2)
            self.channel_dim = -1
            self.wb_shape = (1, 1, 1, -1)
        else:
            self.spatial_dim = (2, 3)
            self.channel_dim = 1
            self.wb_shape = (1, -1, 1, 1)
        self.weight = nn.Parameter(torch.zeros(dim, **dd))
        self.bias = nn.Parameter(torch.zeros(dim, **dd))

    def forward(self, x):
        x_g = x.norm(p=2, dim=self.spatial_dim, keepdim=True)
        x_n = x_g / (x_g.mean(dim=self.channel_dim, keepdim=True) + self.eps)
        return x + torch.addcmul(self.bias.view(self.wb_shape), self.weight.view(self.wb_shape), x * x_n)
