# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.layer_scale
# (timm 1.0.22, source sha256 499631e59c5ae5d2).  Do not edit; change the spec.
# Kept: LayerScale, LayerScale2d
from __future__ import absolute_import, division, print_function
import torch
from torch import nn

class LayerScale(nn.Module):
    """ LayerScale on tensors with channels in last-dim.
    """

    def __init__(self, dim, init_values=1e-05, inplace=False, device=None, dtype=None):
        super(LayerScale, self).__init__()
        self.init_values = init_values
        self.inplace = inplace
        self.gamma = nn.Parameter(torch.empty(dim, device=device, dtype=dtype))
        self.reset_parameters()

    def reset_parameters(self):
        torch.nn.init.constant_(self.gamma, self.init_values)

    def forward(self, x):
        return x.mul_(self.gamma) if self.inplace else x * self.gamma

class LayerScale2d(nn.Module):
    """ LayerScale for tensors with torch 2D NCHW layout.
    """

    def __init__(self, dim, init_values=1e-05, inplace=False, device=None, dtype=None):
        super(LayerScale2d, self).__init__()
        self.init_values = init_values
        self.inplace = inplace
        self.gamma = nn.Parameter(torch.empty(dim, device=device, dtype=dtype))
        self.reset_parameters()

    def reset_parameters(self):
        torch.nn.init.constant_(self.gamma, self.init_values)

    def forward(self, x):
        gamma = self.gamma.view(1, -1, 1, 1)
        return x.mul_(gamma) if self.inplace else x * gamma
