# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.linear
# (timm 1.0.22, source sha256 6da4b65a9974bd81).  Do not edit; change the spec.
# Kept: Linear
from __future__ import absolute_import, division, print_function
import torch
import torch.nn.functional as F
from torch import nn as nn

class Linear(nn.Linear):
    """Applies a linear transformation to the incoming data: :math:`y = xA^T + b`

    Wraps torch.nn.Linear to support AMP + torchscript usage by manually casting
    weight & bias to input.dtype to work around an issue w/ torch.addmm in this use case.
    """

    def forward(self, input):
        if torch.jit.is_scripting():
            bias = self.bias.to(dtype=input.dtype) if self.bias is not None else None
            return F.linear(input, self.weight.to(dtype=input.dtype), bias=bias)
        else:
            return F.linear(input, self.weight, self.bias)
