# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.norm
# (timm 1.0.22, source sha256 afe3abf01a437906).  Do not edit; change the spec.
# Kept: GroupNorm, GroupNorm1, LayerNorm, LayerNorm2d, LayerNormFp32, LayerNorm2dFp32, RmsNorm, RmsNorm2d, RmsNormFp32, RmsNorm2dFp32, SimpleNorm, SimpleNorm2d, SimpleNormFp32, SimpleNorm2dFp32
#   rms_norm left unbound: bound by a top-level try-import; read by RmsNorm.forward, which no ported model builds
from __future__ import absolute_import, division, print_function
import numbers
import torch
import torch.nn as nn
import torch.nn.functional as F
from timm.layers.fast_norm import is_fast_norm, fast_group_norm, fast_layer_norm, fast_rms_norm, rms_norm2d, fast_rms_norm2d, fast_simple_norm, simple_norm

class GroupNorm(nn.GroupNorm):

    def __init__(self, num_channels, num_groups=32, eps=1e-05, affine=True, **kwargs):
        super(GroupNorm, self).__init__(num_groups, num_channels, eps=eps, affine=affine, **kwargs)
        self._fast_norm = is_fast_norm()

    def forward(self, x):
        if self._fast_norm:
            return fast_group_norm(x, self.num_groups, self.weight, self.bias, self.eps)
        else:
            return F.group_norm(x, self.num_groups, self.weight, self.bias, self.eps)

class GroupNorm1(nn.GroupNorm):
    """ Group Normalization with 1 group.
    Input: tensor in shape [B, C, *]
    """

    def __init__(self, num_channels, **kwargs):
        super(GroupNorm1, self).__init__(1, num_channels, **kwargs)
        self._fast_norm = is_fast_norm()

    def forward(self, x):
        if self._fast_norm:
            return fast_group_norm(x, self.num_groups, self.weight, self.bias, self.eps)
        else:
            return F.group_norm(x, self.num_groups, self.weight, self.bias, self.eps)

class LayerNorm(nn.LayerNorm):
    """ LayerNorm w/ fast norm option
    """

    def __init__(self, num_channels, eps=1e-06, affine=True, **kwargs):
        super(LayerNorm, self).__init__(num_channels, eps=eps, elementwise_affine=affine, **kwargs)
        self._fast_norm = is_fast_norm()

    def forward(self, x):
        if self._fast_norm:
            x = fast_layer_norm(x, self.normalized_shape, self.weight, self.bias, self.eps)
        else:
            x = F.layer_norm(x, self.normalized_shape, self.weight, self.bias, self.eps)
        return x

class LayerNormFp32(nn.LayerNorm):
    """ LayerNorm
    """

    def __init__(self, num_channels, eps=1e-06, affine=True, **kwargs):
        super(LayerNormFp32, self).__init__(num_channels, eps=eps, elementwise_affine=affine, **kwargs)

    def forward(self, x):
        weight = self.weight.float() if self.weight is not None else None
        bias = self.bias.float() if self.bias is not None else None
        x = F.layer_norm(x.float(), self.normalized_shape, weight, bias, self.eps).to(x.dtype)
        return x

class LayerNorm2d(nn.LayerNorm):
    """ LayerNorm for channels of '2D' spatial NCHW tensors """

    def __init__(self, num_channels, eps=1e-06, affine=True, **kwargs):
        super(LayerNorm2d, self).__init__(num_channels, eps=eps, elementwise_affine=affine, **kwargs)
        self._fast_norm = is_fast_norm()

    def forward(self, x):
        x = x.permute(0, 2, 3, 1)
        if self._fast_norm:
            x = fast_layer_norm(x, self.normalized_shape, self.weight, self.bias, self.eps)
        else:
            x = F.layer_norm(x, self.normalized_shape, self.weight, self.bias, self.eps)
        x = x.permute(0, 3, 1, 2)
        return x

class LayerNorm2dFp32(nn.LayerNorm):
    """ LayerNorm for channels of '2D' spatial NCHW tensors """

    def __init__(self, num_channels, eps=1e-06, affine=True, **kwargs):
        super(LayerNorm2dFp32, self).__init__(num_channels, eps=eps, elementwise_affine=affine, **kwargs)

    def forward(self, x):
        x = x.permute(0, 2, 3, 1)
        weight = self.weight.float() if self.weight is not None else None
        bias = self.bias.float() if self.bias is not None else None
        x = F.layer_norm(x.float(), self.normalized_shape, weight, bias, self.eps).to(x.dtype)
        x = x.permute(0, 3, 1, 2)
        return x

class RmsNorm(nn.Module):
    """ RmsNorm w/ fast (apex) norm if available
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine', '_fast_norm']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(RmsNorm, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        self._fast_norm = is_fast_norm()
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        if self._fast_norm:
            x = fast_rms_norm(x, self.normalized_shape, self.weight, self.eps)
        else:
            x = rms_norm(x, self.normalized_shape, self.weight, self.eps)
        return x

class RmsNormFp32(nn.Module):
    """ RmsNorm w/ fast (apex) norm if available
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(RmsNormFp32, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        weight = self.weight.float() if self.weight is not None else None
        x = rms_norm(x.float(), self.normalized_shape, weight, self.eps).to(x.dtype)
        return x

class RmsNorm2d(nn.Module):
    """ RmsNorm2D for NCHW tensors, w/ fast apex or cast norm if available

    NOTE: It's currently (2025-05-10) faster to use an eager 2d kernel that does reduction
    on dim=1 than to permute and use internal PyTorch F.rms_norm, this may change if something
    like https://github.com/pytorch/pytorch/pull/150576 lands.
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine', '_fast_norm']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(RmsNorm2d, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        self._fast_norm = is_fast_norm()
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        if self._fast_norm:
            x = fast_rms_norm2d(x, self.normalized_shape, self.weight, self.eps)
        else:
            x = rms_norm2d(x, self.normalized_shape, self.weight, self.eps)
        return x

class RmsNorm2dFp32(nn.Module):
    """ RmsNorm2D for NCHW tensors, w/ fast apex or cast norm if available

    NOTE: It's currently (2025-05-10) faster to use an eager 2d kernel that does reduction
    on dim=1 than to permute and use internal PyTorch F.rms_norm, this may change if something
    like https://github.com/pytorch/pytorch/pull/150576 lands.
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(RmsNorm2dFp32, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        weight = self.weight.float() if self.weight is not None else None
        x = rms_norm2d(x.float(), self.normalized_shape, weight, self.eps).to(x.dtype)
        return x

class SimpleNorm(nn.Module):
    """ SimpleNorm (x / std(x))
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine', '_fast_norm']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(SimpleNorm, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        self._fast_norm = is_fast_norm()
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        if self._fast_norm:
            x = fast_simple_norm(x, self.normalized_shape, self.weight, self.eps)
        else:
            x = simple_norm(x, self.normalized_shape, self.weight, self.eps)
        return x

class SimpleNormFp32(nn.Module):
    """ SimpleNorm (x / std(x))
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(SimpleNormFp32, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        weight = self.weight.float() if self.weight is not None else None
        x = simple_norm(x.float(), self.normalized_shape, weight, self.eps).to(x.dtype)
        return x

class SimpleNorm2d(nn.Module):
    """ SimpleNorm for NCHW tensors
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine', '_fast_norm']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(SimpleNorm2d, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        self._fast_norm = is_fast_norm()
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        x = x.permute(0, 2, 3, 1)
        if self._fast_norm:
            x = fast_simple_norm(x, self.normalized_shape, self.weight, self.eps)
        else:
            x = simple_norm(x, self.normalized_shape, self.weight, self.eps)
        x = x.permute(0, 3, 1, 2)
        return x

class SimpleNorm2dFp32(nn.Module):
    """ SimpleNorm for NCHW tensors
    """
    __constants__ = ['normalized_shape', 'eps', 'elementwise_affine']

    def __init__(self, channels, eps=1e-06, affine=True, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(SimpleNorm2dFp32, self).__init__()
        normalized_shape = channels
        if isinstance(normalized_shape, numbers.Integral):
            normalized_shape = (normalized_shape,)
        self.normalized_shape = tuple(normalized_shape)
        self.eps = eps
        self.elementwise_affine = affine
        if self.elementwise_affine:
            self.weight = nn.Parameter(torch.empty(self.normalized_shape, **dd))
        else:
            self.register_parameter('weight', None)
        self.reset_parameters()

    def reset_parameters(self):
        if self.elementwise_affine:
            nn.init.ones_(self.weight)

    def forward(self, x):
        x = x.permute(0, 2, 3, 1)
        weight = self.weight.float() if self.weight is not None else None
        x = simple_norm(x.float(), self.normalized_shape, weight, self.eps).to(x.dtype)
        x = x.permute(0, 3, 1, 2)
        return x
