# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.patch_embed
# (timm 1.0.22, source sha256 7b7e670f8e6a2828).  Do not edit; change the spec.
# Kept: PatchEmbed, resample_patch_embed
from __future__ import absolute_import, division, print_function
import math
import torch
from torch import nn as nn
import torch.nn.functional as F
from timm.layers.format import Format, nchw_to
from timm.layers.helpers import to_2tuple
from timm.layers.trace_utils import _assert

class PatchEmbed(nn.Module):
    """ 2D Image to Patch Embedding
    """

    def __init__(self, img_size=224, patch_size=16, in_chans=3, embed_dim=768, norm_layer=None, flatten=True, output_fmt=None, bias=True, strict_img_size=True, dynamic_img_pad=False, device=None, dtype=None):
        dd = {'device': device, 'dtype': dtype}
        super(PatchEmbed, self).__init__()
        self.patch_size = to_2tuple(patch_size)
        self.img_size, self.grid_size, self.num_patches = self._init_img_size(img_size)
        if output_fmt is not None:
            self.flatten = False
            self.output_fmt = Format(output_fmt)
        else:
            self.flatten = flatten
            self.output_fmt = Format.NCHW
        self.strict_img_size = strict_img_size
        self.dynamic_img_pad = dynamic_img_pad
        self.proj = nn.Conv2d(in_chans, embed_dim, kernel_size=patch_size, stride=patch_size, bias=bias, **dd)
        self.norm = norm_layer(embed_dim, **dd) if norm_layer else nn.Identity()

    def _init_img_size(self, img_size):
        assert self.patch_size
        if img_size is None:
            return (None, None, None)
        img_size = to_2tuple(img_size)
        grid_size = tuple([s // p for s, p in zip(img_size, self.patch_size)])
        num_patches = grid_size[0] * grid_size[1]
        return (img_size, grid_size, num_patches)

    def set_input_size(self, img_size=None, patch_size=None):
        new_patch_size = None
        if patch_size is not None:
            new_patch_size = to_2tuple(patch_size)
        if new_patch_size is not None and new_patch_size != self.patch_size:
            with torch.no_grad():
                new_proj = nn.Conv2d(self.proj.in_channels, self.proj.out_channels, kernel_size=new_patch_size, stride=new_patch_size, bias=self.proj.bias is not None, device=self.proj.weight.device, dtype=self.proj.weight.dtype)
                new_proj.weight.copy_(resample_patch_embed(self.proj.weight, new_patch_size, verbose=True))
                if self.proj.bias is not None:
                    new_proj.bias.copy_(self.proj.bias)
                self.proj = new_proj
            self.patch_size = new_patch_size
        img_size = img_size or self.img_size
        if img_size != self.img_size or new_patch_size is not None:
            self.img_size, self.grid_size, self.num_patches = self._init_img_size(img_size)

    def feat_ratio(self, as_scalar=True):
        if as_scalar:
            return max(self.patch_size)
        else:
            return self.patch_size

    def dynamic_feat_size(self, img_size):
        """ Get grid (feature) size for given image size taking account of dynamic padding.
        NOTE: must be torchscript compatible so using fixed tuple indexing
        """
        if self.dynamic_img_pad:
            return (math.ceil(img_size[0] / self.patch_size[0]), math.ceil(img_size[1] / self.patch_size[1]))
        else:
            return (img_size[0] // self.patch_size[0], img_size[1] // self.patch_size[1])

    def forward(self, x):
        B, C, H, W = x.shape
        if self.img_size is not None:
            if self.strict_img_size:
                _assert(H == self.img_size[0], "Input height ({0}) doesn't match model ({1}).".format(H, self.img_size[0]))
                _assert(W == self.img_size[1], "Input width ({0}) doesn't match model ({1}).".format(W, self.img_size[1]))
            elif not self.dynamic_img_pad:
                _assert(H % self.patch_size[0] == 0, 'Input height ({0}) should be divisible by patch size ({1}).'.format(H, self.patch_size[0]))
                _assert(W % self.patch_size[1] == 0, 'Input width ({0}) should be divisible by patch size ({1}).'.format(W, self.patch_size[1]))
        if self.dynamic_img_pad:
            pad_h = (self.patch_size[0] - H % self.patch_size[0]) % self.patch_size[0]
            pad_w = (self.patch_size[1] - W % self.patch_size[1]) % self.patch_size[1]
            x = F.pad(x, (0, pad_w, 0, pad_h))
        x = self.proj(x)
        if self.flatten:
            x = x.flatten(2).transpose(1, 2)
        elif self.output_fmt != Format.NCHW:
            x = nchw_to(x, self.output_fmt)
        x = self.norm(x)
        return x
DTYPE_INTERMEDIATE = torch.float32

def _compute_resize_matrix(old_size, new_size, interpolation, antialias, device, dtype=DTYPE_INTERMEDIATE):
    """Computes the resize matrix basis vectors and interpolates them to new_size."""
    old_h, old_w = old_size
    new_h, new_w = new_size
    old_total = old_h * old_w
    new_total = new_h * new_w
    eye_matrix = torch.eye(old_total, device=device, dtype=dtype)
    basis_vectors_batch = eye_matrix.reshape(old_total, 1, old_h, old_w)
    resized_basis_vectors_batch = F.interpolate(basis_vectors_batch, size=new_size, mode=interpolation, antialias=antialias, align_corners=False)
    resize_matrix = resized_basis_vectors_batch.squeeze(1).permute(1, 2, 0).reshape(new_total, old_total)
    return resize_matrix

def _apply_resampling(patch_embed, pinv_matrix, new_size_tuple, orig_dtype, intermediate_dtype=DTYPE_INTERMEDIATE):
    """ Simplified resampling w/o vmap use.
    As proposed by https://github.com/stas-sl
    """
    c_out, c_in, _ = (lambda _t: _t[:2] + (list(_t[2:len(_t) - 0]),) + _t[len(_t) - 0:])(tuple(patch_embed.shape))
    patch_embed = patch_embed.reshape(c_out, c_in, -1).to(dtype=intermediate_dtype)
    pinv_matrix = pinv_matrix.to(dtype=intermediate_dtype)
    resampled_patch_embed = patch_embed.__matmul__(pinv_matrix)
    resampled_patch_embed = resampled_patch_embed.reshape(c_out, c_in, *new_size_tuple).to(dtype=orig_dtype)
    return resampled_patch_embed

def resample_patch_embed(patch_embed, new_size, interpolation='bicubic', antialias=True, verbose=False):
    """ Standalone function (computes matrix on each call). """
    assert len(patch_embed.shape) == 4, 'Input tensor should be 4D (out_ch, in_ch, h, w)'
    assert len(new_size) == 2, 'New shape should only be hw (height, width)'
    old_size_tuple = tuple(patch_embed.shape[-2:])
    new_size_tuple = tuple(new_size)
    if old_size_tuple == new_size_tuple:
        return patch_embed
    device = patch_embed.device
    orig_dtype = patch_embed.dtype
    resize_mat = _compute_resize_matrix(old_size_tuple, new_size_tuple, interpolation, antialias, device, DTYPE_INTERMEDIATE)
    pinv_matrix = torch.linalg.pinv(resize_mat)
    resampled_patch_embed = _apply_resampling(patch_embed, pinv_matrix, new_size_tuple, orig_dtype, DTYPE_INTERMEDIATE)
    return resampled_patch_embed
