# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.pos_embed_sincos
# (timm 1.0.22, source sha256 fec482a96a7a7400).  Do not edit; change the spec.
# Kept: apply_rot_embed, RotaryEmbedding
from __future__ import absolute_import, division, print_function
import math
import torch
from torch import nn as nn

def pixel_freq_bands(num_bands, max_freq=224.0, linear_bands=True, device=None):
    if linear_bands:
        bands = torch.linspace(1.0, max_freq / 2, num_bands, dtype=torch.float32, device=device)
    else:
        bands = 2 ** torch.linspace(0, math.log(max_freq, 2) - 1, num_bands, dtype=torch.float32, device=device)
    return bands * torch.pi

def freq_bands(num_bands, temperature=10000.0, step=2, device=None):
    exp = torch.arange(0, num_bands, step, dtype=torch.int64, device=device).to(torch.float32) / num_bands
    bands = 1.0 / temperature ** exp
    return bands

def swap_shape_xy(seq):
    if len(seq) < 2:
        return seq
    return [seq[1], seq[0]] + list(seq[2:])

def build_fourier_pos_embed(feat_shape, bands=None, num_bands=64, max_res=224, temperature=10000.0, linear_bands=False, include_grid=False, in_pixels=True, ref_feat_shape=None, grid_offset=0.0, grid_indexing='ij', device=None, dtype=torch.float32):
    """

    Args:
        feat_shape: Feature shape for embedding.
        bands: Pre-calculated frequency bands.
        num_bands: Number of frequency bands (determines output dim).
        max_res: Maximum resolution for pixel based freq.
        temperature: Temperature for non-pixel freq.
        linear_bands: Linear band spacing for pixel based freq.
        include_grid: Include the spatial grid in output.
        in_pixels: Output in pixel freq.
        ref_feat_shape: Reference feature shape for resize / fine-tune.
        grid_offset: Constant offset to add to grid for non-pixel freq.
        grid_indexing: Indexing mode for meshgrid ('ij' or 'xy')
        dtype: Output dtype.
        device: Output device.

    Returns:

    """
    if bands is None:
        if in_pixels:
            bands = pixel_freq_bands(num_bands, float(max_res), linear_bands=linear_bands, device=device)
        else:
            bands = freq_bands(num_bands, temperature=temperature, step=1, device=device)
    else:
        if device is None:
            device = bands.device
        if dtype is None:
            dtype = bands.dtype
    if grid_indexing == 'xy':
        feat_shape = swap_shape_xy(feat_shape)
        if ref_feat_shape is not None:
            ref_feat_shape = swap_shape_xy(ref_feat_shape)
    if in_pixels:
        t = [torch.linspace(-1.0, 1.0, steps=s, device=device, dtype=torch.float32) for s in feat_shape]
    else:
        t = [torch.arange(s, device=device, dtype=torch.int64).to(torch.float32) + grid_offset for s in feat_shape]
    if ref_feat_shape is not None:
        t = [x / f * r for x, f, r in zip(t, feat_shape, ref_feat_shape)]
    grid = torch.stack(torch.meshgrid(t, indexing=grid_indexing), dim=-1)
    grid = grid.unsqueeze(-1)
    pos = grid * bands
    pos_sin, pos_cos = (pos.sin().to(dtype=dtype), pos.cos().to(dtype=dtype))
    out = [grid, pos_sin, pos_cos] if include_grid else [pos_sin, pos_cos]
    return out

def rot(x):
    return torch.stack([-x[..., 1::2], x[..., ::2]], -1).reshape(x.shape)

def rope_rotate_half(x):
    x1, x2 = x.chunk(2, dim=-1)
    return torch.cat([-x2, x1], dim=-1)

def apply_rot_embed(x, sin_emb, cos_emb, half=False):
    if half:
        return x * cos_emb + rope_rotate_half(x) * sin_emb
    else:
        return x * cos_emb + rot(x) * sin_emb

def build_rotary_pos_embed(feat_shape, bands=None, dim=64, max_res=224, temperature=10000.0, linear_bands=False, in_pixels=True, ref_feat_shape=None, grid_offset=0.0, grid_indexing='ij', device=None, dtype=torch.float32):
    """

    Args:
        feat_shape: Spatial shape of the target tensor for embedding.
        bands: Optional pre-generated frequency bands
        dim: Output dimension of embedding tensor.
        max_res: Maximum resolution for pixel mode.
        temperature: Temperature (inv freq) for non-pixel mode
        linear_bands: Linearly (instead of log) spaced bands for pixel mode
        in_pixels: Pixel vs language (inv freq) mode.
        ref_feat_shape: Reference feature shape for resize / fine-tune.
        grid_offset: Constant offset to add to grid for non-pixel freq.
        grid_indexing: Indexing mode for meshgrid ('ij' or 'xy')
        device: Output device.
        dtype: Output dtype.

    Returns:

    """
    sin_emb, cos_emb = build_fourier_pos_embed(feat_shape, bands=bands, num_bands=dim // 4, max_res=max_res, temperature=temperature, linear_bands=linear_bands, in_pixels=in_pixels, ref_feat_shape=ref_feat_shape, grid_offset=grid_offset, grid_indexing=grid_indexing, device=device, dtype=dtype)
    num_spatial_dim = 1
    for x in feat_shape:
        num_spatial_dim *= x
    sin_emb = sin_emb.reshape(num_spatial_dim, -1).repeat_interleave(2, -1)
    cos_emb = cos_emb.reshape(num_spatial_dim, -1).repeat_interleave(2, -1)
    return (sin_emb, cos_emb)

class RotaryEmbedding(nn.Module):
    """ Rotary position embedding

    NOTE: This is my initial attempt at impl rotary embedding for spatial use, it has not
    been well tested, and will likely change. It will be moved to its own file.

    The following impl/resources were referenced for this impl:
    * https://github.com/lucidrains/vit-pytorch/blob/6f3a5fcf0bca1c5ec33a35ef48d97213709df4ba/vit_pytorch/rvt.py
    * https://blog.eleuther.ai/rotary-embeddings/
    """

    def __init__(self, dim, max_res=224, temperature=10000, in_pixels=True, linear_bands=False, feat_shape=None, ref_feat_shape=None, grid_offset=0.0, grid_indexing='ij', device=None, dtype=None):
        super(RotaryEmbedding, self).__init__()
        self.dim = dim
        self.max_res = max_res
        self.temperature = temperature
        self.linear_bands = linear_bands
        self.in_pixels = in_pixels
        self.feat_shape = feat_shape
        self.ref_feat_shape = ref_feat_shape
        self.grid_offset = grid_offset
        self.grid_indexing = grid_indexing
        if feat_shape is None:
            if in_pixels:
                bands = pixel_freq_bands(dim // 4, float(max_res), linear_bands=linear_bands)
            else:
                bands = freq_bands(dim // 4, temperature=temperature, step=1)
            self.register_buffer('bands', bands.to(device=device, dtype=dtype), persistent=False)
            self.pos_embed_sin = None
            self.pos_embed_cos = None
        else:
            emb_sin, emb_cos = self._get_pos_embed_values(feat_shape, device=device, dtype=dtype)
            self.bands = None
            self.register_buffer('pos_embed_sin', emb_sin, persistent=False)
            self.register_buffer('pos_embed_cos', emb_cos, persistent=False)

    def _get_pos_embed_values(self, feat_shape, device=None, dtype=torch.float32):
        emb_sin, emb_cos = build_rotary_pos_embed(feat_shape=feat_shape, dim=self.dim, max_res=self.max_res, temperature=self.temperature, linear_bands=self.linear_bands, in_pixels=self.in_pixels, ref_feat_shape=self.ref_feat_shape, grid_offset=self.grid_offset, grid_indexing=self.grid_indexing, device=device, dtype=dtype)
        return (emb_sin, emb_cos)

    def update_feat_shape(self, feat_shape):
        if self.feat_shape is not None and feat_shape != self.feat_shape:
            assert self.pos_embed_sin is not None
            assert self.pos_embed_cos is not None
            self.pos_embed_sin, self.pos_embed_cos = self._get_pos_embed_values(feat_shape, device=self.pos_embed_sin.device, dtype=self.pos_embed_sin.dtype)
            self.feat_shape = feat_shape

    def get_embed(self, shape=None):
        if shape is not None and self.bands is not None:
            return build_rotary_pos_embed(shape, self.bands, in_pixels=self.in_pixels, ref_feat_shape=self.ref_feat_shape, grid_offset=self.grid_offset, grid_indexing=self.grid_indexing)
        elif self.pos_embed_sin is not None and self.pos_embed_cos is not None:
            return (self.pos_embed_sin, self.pos_embed_cos)
        else:
            assert False, 'get_embed() requires pre-computed pos embeds or valid shape w/ pre-computed bands'

    def forward(self, x):
        sin_emb, cos_emb = self.get_embed(x.shape[2:])
        return apply_rot_embed(x, sin_emb, cos_emb)
