# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.layers.pos_embed
# (timm 1.0.22, source sha256 8e5beda55289ff7a).  Do not edit; change the spec.
# Kept: resample_abs_pos_embed, resample_abs_pos_embed_nhwc
from __future__ import absolute_import, division, print_function
import logging
import math
import torch
import torch.nn.functional as F
from timm.layers._fx import register_notrace_function
_logger = logging.getLogger(__name__)

@torch.fx.wrap
@register_notrace_function
def resample_abs_pos_embed(posemb, new_size, old_size=None, num_prefix_tokens=1, interpolation='bicubic', antialias=True, verbose=False):
    num_pos_tokens = posemb.shape[1]
    num_new_tokens = new_size[0] * new_size[1] + num_prefix_tokens
    if num_new_tokens == num_pos_tokens and new_size[0] == new_size[1]:
        return posemb
    if old_size is None:
        hw = int(math.sqrt(num_pos_tokens - num_prefix_tokens))
        old_size = (hw, hw)
    if num_prefix_tokens:
        posemb_prefix, posemb = (posemb[:, :num_prefix_tokens], posemb[:, num_prefix_tokens:])
    else:
        posemb_prefix, posemb = (None, posemb)
    embed_dim = posemb.shape[-1]
    orig_dtype = posemb.dtype
    posemb = posemb.float()
    posemb = posemb.reshape(1, old_size[0], old_size[1], -1).permute(0, 3, 1, 2)
    posemb = F.interpolate(posemb, size=new_size, mode=interpolation, antialias=antialias)
    posemb = posemb.permute(0, 2, 3, 1).reshape(1, -1, embed_dim)
    posemb = posemb.to(orig_dtype)
    if posemb_prefix is not None:
        posemb = torch.cat([posemb_prefix, posemb], dim=1)
    if not torch.jit.is_scripting() and verbose:
        _logger.info('Resized position embedding: {0} to {1}.'.format(old_size, new_size))
    return posemb

@torch.fx.wrap
@register_notrace_function
def resample_abs_pos_embed_nhwc(posemb, new_size, interpolation='bicubic', antialias=True, verbose=False):
    if new_size[0] == posemb.shape[-3] and new_size[1] == posemb.shape[-2]:
        return posemb
    orig_dtype = posemb.dtype
    posemb = posemb.float()
    posemb = posemb.reshape(1, posemb.shape[-3], posemb.shape[-2], posemb.shape[-1]).permute(0, 3, 1, 2)
    posemb = F.interpolate(posemb, size=new_size, mode=interpolation, antialias=antialias)
    posemb = posemb.permute(0, 2, 3, 1).to(orig_dtype)
    if not torch.jit.is_scripting() and verbose:
        _logger.info('Resized position embedding: {0} to {1}.'.format(posemb.shape[-3:-1], new_size))
    return posemb
