"""timm, as far as the ported model files reach, for the eval forward the
PyTorch 2 dashboard runs.

Files whose header says "Generated by benchmark/suites/port.py" are upstream
timm source through the porter's syntax-only rewrites.  The others are
hand-written stand-ins for upstream modules that have no Python 2 form
(an Enum, top-level try/except imports and if/else configuration, star
imports, dataclass configs) or whose work is done elsewhere here (weight
download and initialisation: every tensor comes from the checkpoint through
load_state_dict).  Each follows upstream on the path an eval forward and
create_model take, and raises NotImplementedError on any other path.
Environment queries (fused attention, torch features) answer as the
reference torch run answers them, so the ported code takes the branch the
reference took.

    layers/__init__.py, layers/config.py, layers/create_act.py,
    layers/format.py, layers/helpers.py, layers/trace_utils.py,
    layers/_fx.py, layers/weight_init.py,
    models/__init__.py, models/_builder.py, models/_factory.py,
    models/_registry.py
"""
__version__ = "1.0.22"

from timm.layers import (is_scriptable, is_exportable, set_scriptable,
                         set_exportable)
from timm.models import (create_model, is_model, model_entrypoint,
                         get_pretrained_cfg)
