"""torchvision, as far as the ported torchvision models reach.  Files with a
"Generated by benchmark/suites/port.py" header are upstream source through
the porter; this package init and the empty sub-package inits are the only
hand-written parts."""
