# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from torchvision.utils
# (torchvision 0.29.0+cu130, source sha256 5a0a5d9aa6b0c7d7).  Do not edit; change the spec.
# Kept: _make_ntuple
from __future__ import absolute_import, division, print_function
import collections
from itertools import repeat

def _make_ntuple(x, n):
    """
    Make n-tuple from input x. If x is an iterable, then we just convert it to tuple.
    Otherwise, we will make a tuple of length n, all with value of x.
    reference: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/utils.py#L8

    Args:
        x (Any): input value
        n (int): length of the resulting tuple
    """
    if isinstance(x, collections.abc.Iterable):
        return tuple(x)
    return tuple(repeat(x, n))
