# -*- coding: utf-8 -*-
# Generated by benchmark/suites/port.py from timm.utils.model
# (timm 1.0.22, source sha256 cbd0ae079c31bbde).  Do not edit; change the spec.
# Kept: reparameterize_model
from __future__ import absolute_import, division, print_function
from copy import deepcopy

def reparameterize_model(model, inplace=False):
    if not inplace:
        model = deepcopy(model)

    def _fuse(m):
        for child_name, child in m.named_children():
            if hasattr(child, 'fuse'):
                setattr(m, child_name, child.fuse())
            elif hasattr(child, 'reparameterize'):
                child.reparameterize()
            elif hasattr(child, 'switch_to_deploy'):
                child.switch_to_deploy()
            _fuse(child)
    _fuse(model)
    return model
