name: Named Branches
on: push
jobs:
  named_branches:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
    - uses: Julian/named-branch-action@main
      with:
        github_token: '${{ secrets.GITHUB_TOKEN }}'
