name: PyTest Metainterp and Codewriter

on:
  push:
    branches: [ "tristate", "tristate-experimental", "main", "master" ]
  pull_request:
    branches: [ "tristate", "tristate-experimental", "main", "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 2.7
      uses: MatteoH2O1999/setup-python@v2
      with:
        python-version: "2.7"
    - name: Checkout PyPy
      uses: actions/checkout@v3
      with:
        repository: mozillazg/pypy
        path: pypy
    - name: install dependencies
      run: |
        python -m pip install "hypothesis<4.40" rply attrs setuptools "z3-solver==4.11.2"
        sudo apt install libgc-dev
    - name: Test with pytest
      run: |
        python pypy/pytest.py -v rpython/jit/metainterp/ rpython/jit/codewriter/ rpython/jit/backend/x86/test/test_ztranslation_basic.py --z3-timeout=3000
