name: Rpython Unit Tests
# === Implementation notes ===
# Since the test suite is too large to run in a reasonable amount of time
# we split this into tests by sub-folder within the rpython folder

# Note: this action will only run if there are changes to one of:
#  - rpython folder
#  - .github folder
#  - pytest.py
# add more items to `paths` if we missed some!

on:
  push:
    branches: [ "main", "py3.9", "py3.10" ]
    paths:
        - "rpython/**/*"
        - "pytest.py"
        - ".github/**/*"
  pull_request:
    branches: [ "main", "py3.9", "py3.10" ]
    paths:
      - "rpython/**/*"
      - "pytest.py"
      - ".github/**/*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-misc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test Annotator
      run: pypy2 pytest.py rpython/annotator
    - name: Test Config
      run: pypy2 pytest.py rpython/config
    - name: Test Flowspace
      run: pypy2 pytest.py rpython/flowspace
    - name: Test Tool
      run: pypy2 pytest.py rpython/tool

  test-jit:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test Jit
      run: pypy2 pytest.py rpython/jit

  test-memory:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test Memory
      run: pypy2 pytest.py rpython/memory

  test-rlib:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test RLib
      run: pypy2 pytest.py rpython/rlib

  test-rtyper:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test RTyper
      run: pypy2 pytest.py rpython/rtyper -v

  test-translator:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "pypy2.7-7.3.10"
    - run: |
          echo "Install requirements"
          sudo apt-get install -y libgc-dev
          pypy2 -m pip install --user hypothesis==4.39.3
    - name: Test Translator
      run: pypy2 pytest.py rpython/translator
